// Hitster's texts in English and Hebrew, the language setting, the genres and the song-language groups.
// Everything Hitster shows comes from here (tr), so a new screen is in both languages from the start.
import { store } from '../js/core/store.js';

/** Hitster's language: 'he' or 'en' (setting hitsterLang; 'auto' = the on-screen keyboard's language). */
export function hitsterLang() {
  const v = store.get('hitsterLang');
  if (v === 'en' || v === 'he') return v;
  return store.get('kbdLang') === 'he' ? 'he' : 'en';
}

/** The genre chips (ids are what the songs' g: [...] tags use). */
export const GENRES = [
  { id: 'pop', en: 'Pop', he: 'פופ' },
  { id: 'rock', en: 'Rock', he: 'רוק' },
  { id: 'hiphop', en: 'Hip-hop / Rap', he: 'היפ־הופ / ראפ' },
  { id: 'rnb', en: 'R&B / Soul', he: 'R&B / סול' },
  { id: 'dance', en: 'Dance / Electronic', he: 'דאנס / אלקטרוני' },
  { id: 'disco', en: 'Disco / Funk', he: 'דיסקו / פאנק' },
  { id: 'country', en: 'Country / Folk', he: 'קאנטרי / פולק' },
  { id: 'metal', en: 'Metal', he: 'מטאל' },
  { id: 'latin', en: 'Latin', he: 'לטיני' },
  { id: 'reggae', en: 'Reggae', he: 'רגאיי' },
  { id: 'jazz', en: 'Jazz / Blues', he: 'ג׳אז / בלוז' },
  { id: 'mizrahi', en: 'Mizrahi', he: 'מזרחית' },
  { id: 'israeli', en: 'Israeli rock / pop', he: 'רוק / פופ ישראלי' },
  { id: 'eurovision', en: 'Eurovision', he: 'אירוויזיון' },
  { id: 'soundtrack', en: 'Musical / Soundtrack', he: 'מחזמר / פסקול' },
  { id: 'children', en: 'Children', he: 'ילדים' },
];
/** Song-language groups: a song's l is 'en', 'he' or anything else (= 'other'). */
export const SONG_LANGS = [{ id: 'en', en: 'English', he: 'אנגלית' }, { id: 'he', en: 'Hebrew', he: 'עברית' }, { id: 'other', en: 'Other', he: 'אחרות' }];

const TXT = {
  en: {
    howTo: 'A mystery song plays — place it in your timeline by year: before, between or after your cards. Right spot = you keep the card.',
    howToBingo: 'Spin the wheel for a question, listen, answer — then cross a box of that colour on your card. First to complete a line wins.',
    original: 'Original', classic: 'Classic', bingo: 'Bingo', coop: 'Co-op / Solo',
    party: 'Party', solo: 'Solo', team: 'Team', goal: 'Win at', cards5: '5 cards', songs: 'Songs', rules: 'Rules', level: 'Level', players: 'Players',
    rulesStd: 'Standard', rulesPro: 'Pro', rulesExpert: 'Expert', lvlBeginner: 'Beginner', lvlExpert: 'Expert',
    deckAll: 'All', deckIl: 'Israeli hits', deckOld: '60s–80s', deckNew: '90s–now', deckLib: 'Your library',
    eraAll: 'All decades', eraIl: 'Israeli hits', eraOld: '60s–80s', eraNew: '90s–now', eraLib: 'Your library', eraDemo: 'Demo songs',
    unit: 'cards', unitRounds: 'songs', yourService: 'your music service', you: 'You', player: (n) => `Player ${n}`,
    noSvc: 'No music service', noSvcNote: 'Choose a music service first (Rhythm → pick a service), then start Hitster.',
    cantSearch: (svc) => `${svc} can’t search`,
    cantSearchNote: (svc) => `Hitster finds each song by searching ${svc}, which this service can’t do here. Use Spotify, Apple Music, YouTube Music, Plex, Jellyfin — or Demo to try the game.`,
    noYears: (svc) => `${svc} has no song years — using the song list`,
    loadingPl: 'Loading your playlists…', noPl: (svc) => `No playlists found on ${svc}.`, plErr: 'Couldn’t load your playlists.',
    reading: (n) => `Reading “${n}”…`, fewSongs: (n) => `“${n}” has too few songs with a release year — pick another.`, readErr: 'Couldn’t read that playlist.',
    finding: 'Finding a song…', starting: 'Starting the music…', playErr: (svc) => `${svc} couldn’t play the song.`,
    notFoundAll: (svc) => `Couldn’t find these songs on ${svc}.`, notOn: (svc) => `Not on ${svc} — drawing another…`,
    wins: (n) => `${n} wins!`, board: (b) => `Cards — ${b}`, strikesT: 'Three strikes!',
    soloNote: (n, k) => `You placed ${n} song${n === 1 ? '' : 's'} — a ${k}-card timeline.`,
    heardAll: 'You heard every song!', heardAllNote: (k) => `A ${k}-card timeline — the deck ran out.`, tie: 'Out of songs — a tie!',
    hintDrag: 'Drag the record to a gap — or tap a gap', hintLock: 'Tap Lock in when you’re sure',
    older: 'older', newer: 'newer', soloStreak: 'Solo streak',
    placedHearts: (n, h) => `${n} placed  ·  ${h}`, cardsOf: (n, goal) => `${n} / ${goal} cards`, ofGoal: (n, goal) => `${n} / ${goal}`,
    whosPlaying: 'Who’s playing?', soloSub: (era) => `${era} · 3 mistakes and you’re out`, partySub: (era, goal) => `${era} · first to ${goal} cards`,
    soloPara: 'Each song you place in the right spot grows your timeline. How long can you go?',
    addPlayer: '+ Add player', skipIntro: '✓ Skip the intro (start at 0:30)', fromStart: '○ Play songs from the start', start: 'Start',
    pickPl: 'Pick a playlist', plFrom: (svc) => `Songs and years from ${svc}`, useList: 'Use the song list instead',
    nextUp: 'Next up', tapPlay: 'Tap to play the song', passDisplay: 'Pass the display', onlyPlayer: 'Only the player whose turn it is looks!',
    retry: 'Try again', another: 'Another song', pickSpot: 'Pick a spot', lockIn: 'Lock in', knew: 'I knew it!', skip: 'Skip',
    notPlaying: 'Not playing? Draw another', dragRec: 'Drag the record into your timeline', token: '+1 token',
    right: 'Right spot — it’s yours!', wrong: 'Not quite!', tapCont: 'Tap to continue',
    placed: (n) => `${n} placed`, strikes: 'Three strikes', nCards: (n) => `${n} cards`,
    // setup: song filters
    songLangs: 'Songs in', genres: 'Genres', genresAll: 'All genres', genresOff: (n) => `${n} blocked`, nSongs: (n) => `${n} songs`,
    tooFew: 'Too few songs — change the filters', update: 'Update songs', settingsBtn: 'Songs',
    genresHint: 'Tap a genre to block it — its songs won’t play', done: 'Done', allowAll: 'Allow all', blocked: 'blocked',
    updTitle: 'Update song lists', updHint: 'Adds more well-known songs from Wikidata. They stay on this device and the list keeps growing.',
    updRun: 'Update now', updAgain: 'Update again', cancel: 'Cancel', back: 'Back',
    updDone: (n) => (n ? `+${n} new songs` : 'No new songs this time'), updErr: 'Couldn’t reach Wikidata. Check the internet connection and try again.',
    updLast: (d) => `Last updated ${d}`, updNever: 'Not updated yet', updCount: (b, x) => `${b} built in · ${x} downloaded`,
    updBusy: (what) => `Fetching ${what}…`, updDecade: (d) => `the ${d}s`, updHe: 'Hebrew songs', updIl: 'Israeli songs', updWorld: 'world hits',
    // Original: tokens, challenges, buying
    hitster: 'HITSTER!', challengeQ: 'Anyone think it’s in the wrong spot?', challengeHint: 'Tap your name, then put a token where it belongs',
    reveal: 'Reveal', pickGap: (n) => `${n}: tap where it really goes`, tokenNone: 'no tokens',
    stole: (n) => `${n} wins the card!`, challengeLost: 'The challenge failed — tokens lost', buy: 'Buy a card', bought: 'Card bought!',
    buyNote: '3 tokens', named: 'Title + artist', wrongName: '✕ Name was wrong', yearQ: 'Exact year', yearMiss: 'Wrong year — the card is lost',
    nameMiss: 'Title + artist not named — the card is lost', cancelChallenge: 'Cancel',
    // Co-op
    whosTeam: 'Who’s on the team?', teamSub: (era, goal) => `${era} · ${goal} cards together · 3 mistakes`,
    teamPara: 'Build one timeline together. Shared tokens, three mistakes.', teamHud: 'Team timeline', everyone: 'Everyone can help!',
    teamWin: 'You did it — together!', teamWinNote: (k, t) => `${k} cards with ${t} token${t === 1 ? '' : 's'} left.`, teamNote: (k) => `The team built a ${k}-card timeline.`,
    teamOf: (n, goal, h) => `${n} / ${goal} cards  ·  ${h}`,
    // Bingo
    bingoSub: (era) => `${era} · first to complete a line`, bingoPara: 'Complete a line on your card — how few songs do you need?',
    round: (n) => `Round ${n}`, tapSpin: 'Tap the wheel to spin', spinning: 'Spinning…', answerNow: 'Answer', listen: 'Listen and think…',
    yourAnswer: (n) => `${n}, your answer`, lock: 'Lock', solo1: 'Solo artist', group1: 'Band / group', before: 'Before 2000', after: '2000 or later',
    sayIt: 'Say it out loud — then reveal!', whoRight: 'Who got it right?', markBox: (n) => `${n}: cross a box`, markSolo: 'Cross a box',
    noFree: (n) => `${n}: no free box in this colour`, line: 'LINE!', bingoWin: (n) => `Bingo for ${n}!`, bingoSolo: 'Bingo!',
    bingoNote: (n) => `A line after ${n} song${n === 1 ? '' : 's'}.`, tieBreak: 'Tie-break: the first one right alone wins', tieShort: 'A tie!',
    nobody: 'Nobody got it this time', okN: (n) => `${n} right`, yourCard: 'your card', crosses: (n) => `${n} crossed`,
    catGroup: 'Solo or band?', catB2000: 'Before 2000?', catY4: '± 4 years', catDecade: 'Decade', catY2: '± 2 years',
    catTitle: 'Song title', catExact: 'Exact year', catArtist: 'Artist', catY3: '± 3 years',
    qGroup: 'Solo artist or band?', qB2000: 'Released before 2000?', qY: (n) => `The year — within ${n} years`, qDecade: 'Which decade?',
    qTitle: 'Name the song!', qExact: 'The exact year', qArtist: 'Who sings it?', decadeName: (d) => `${String(d).slice(2)}s`,
    answerWas: 'Answer', yourN: (n) => `${n}`,
    shGroup: 'Solo/band', shB2000: '< 2000', shY4: '± 4', shDecade: 'Decade', shY2: '± 2', shTitle: 'Title', shYear: 'Year', shArtist: 'Artist', shY3: '± 3',
    spinBtn: 'Spin', soloS: 'Solo', groupS: 'Band', beforeS: '< 2000', afterS: '2000 +', passHint: 'Answer, then pass the display on', continue: 'Continue', tapBox: 'Tap a glowing box',
  },
  he: {
    howTo: 'שיר מסתורי מתנגן — שבצו אותו בציר הזמן שלכם לפי השנה: לפני, בין או אחרי הקלפים שלכם. מקום נכון = הקלף נשאר אצלכם.',
    howToBingo: 'סובבו את הגלגל לשאלה, הקשיבו, ענו — וסמנו משבצת בצבע הזה בכרטיס. מי שמשלים ראשון שורה מנצח.',
    original: 'מקורי', classic: 'קלאסי', bingo: 'בינגו', coop: 'שיתופי / סולו',
    party: 'מסיבה', solo: 'סולו', team: 'קבוצה', goal: 'יעד', cards5: '5 קלפים', songs: 'שירים', rules: 'חוקים', level: 'רמה', players: 'שחקנים',
    rulesStd: 'רגיל', rulesPro: 'מקצוענים', rulesExpert: 'מומחים', lvlBeginner: 'מתחילים', lvlExpert: 'מומחים',
    deckAll: 'הכול', deckIl: 'שירים ישראליים', deckOld: 'ה־60 עד ה־80', deckNew: 'ה־90 עד היום', deckLib: 'הספרייה שלך',
    eraAll: 'כל העשורים', eraIl: 'שירים ישראליים', eraOld: 'שנות ה־60 עד ה־80', eraNew: 'משנות ה־90 עד היום', eraLib: 'הספרייה שלך', eraDemo: 'שירי דמו',
    unit: 'קלפים', unitRounds: 'שירים', yourService: 'שירות המוזיקה שלך', you: 'אני', player: (n) => `שחקן ${n}`,
    noSvc: 'אין שירות מוזיקה', noSvcNote: 'קודם בחרו שירות מוזיקה במסך Rhythm, ואז התחילו את Hitster.',
    cantSearch: (svc) => `אי אפשר לחפש ב־${svc}`,
    cantSearchNote: (svc) => `Hitster מוצא כל שיר בחיפוש ב־${svc}, ושירות זה לא מאפשר חיפוש כאן. השתמשו ב־Spotify, ב־Apple Music, ב־YouTube Music, ב־Plex או ב־Jellyfin — או ב־Demo כדי לנסות את המשחק.`,
    noYears: (svc) => `ב־${svc} אין שנות יציאה — משחקים עם רשימת השירים`,
    loadingPl: 'טוען את הפלייליסטים שלך…', noPl: (svc) => `לא נמצאו פלייליסטים ב־${svc}.`, plErr: 'לא הצלחנו לטעון את הפלייליסטים.',
    reading: (n) => `קורא את „${n}”…`, fewSongs: (n) => `ב„${n}” יש מעט מדי שירים עם שנת יציאה — בחרו פלייליסט אחר.`, readErr: 'לא הצלחנו לקרוא את הפלייליסט.',
    finding: 'מחפש שיר…', starting: 'מפעיל את המוזיקה…', playErr: (svc) => `${svc} לא הצליח לנגן את השיר.`,
    notFoundAll: (svc) => `השירים האלה לא נמצאו ב־${svc}.`, notOn: (svc) => `לא נמצא ב־${svc} — שולפים שיר אחר…`,
    wins: (n) => `ניצחון ל־${n}!`, board: (b) => `קלפים — ${b}`, strikesT: 'שלוש טעויות!',
    soloNote: (n, k) => `שיבצתם ${n === 1 ? 'שיר אחד' : `${n} שירים`} — ציר זמן של ${k} קלפים.`,
    heardAll: 'שמעתם את כל השירים!', heardAllNote: (k) => `ציר זמן של ${k} קלפים — החפיסה נגמרה.`, tie: 'נגמרו השירים — תיקו!',
    hintDrag: 'גררו את התקליט לרווח — או הקישו על רווח', hintLock: 'בטוחים? הקישו על „נעילה”',
    older: 'ישן יותר', newer: 'חדש יותר', soloStreak: 'רצף סולו',
    placedHearts: (n, h) => `${n} שובצו  ·  ${h}`, cardsOf: (n, goal) => `${n} מתוך ${goal} קלפים`, ofGoal: (n, goal) => `${n} מתוך ${goal}`,
    whosPlaying: 'מי משחק?', soloSub: (era) => `${era} · שלוש טעויות ויוצאים`, partySub: (era, goal) => `${era} · הראשון ל־${goal} קלפים מנצח`,
    soloPara: 'כל שיר שתשבצו במקום הנכון מאריך את ציר הזמן שלכם. כמה רחוק תגיעו?',
    addPlayer: '+ הוספת שחקן', skipIntro: '✓ דילוג על הפתיחה (מ־0:30)', fromStart: '○ השירים מתנגנים מההתחלה', start: 'התחלה',
    pickPl: 'בחרו פלייליסט', plFrom: (svc) => `שירים ושנים מ־${svc}`, useList: 'שחקו עם רשימת השירים',
    nextUp: 'התור של', tapPlay: 'הקישו כדי לנגן את השיר', passDisplay: 'העבירו את המסך', onlyPlayer: 'רק מי שתורו מסתכל!',
    retry: 'נסו שוב', another: 'שיר אחר', pickSpot: 'בחרו מקום', lockIn: 'נעילה', knew: 'ידעתי!', skip: 'דילוג',
    notPlaying: 'לא מתנגן? שיר אחר', dragRec: 'גררו את התקליט לציר הזמן', token: '+1 אסימון',
    right: 'מקום נכון — הקלף שלכם!', wrong: 'לא בדיוק!', tapCont: 'הקישו כדי להמשיך',
    placed: (n) => `${n} שובצו`, strikes: 'שלוש טעויות', nCards: (n) => `${n} קלפים`,
    songLangs: 'שירים ב', genres: 'ז׳אנרים', genresAll: 'כל הז׳אנרים', genresOff: (n) => `${n} חסומים`, nSongs: (n) => `${n} שירים`,
    tooFew: 'מעט מדי שירים — שנו את הסינון', update: 'עדכון שירים', settingsBtn: 'שירים',
    genresHint: 'הקישו על ז׳אנר כדי לחסום אותו — השירים שלו לא יתנגנו', done: 'סיום', allowAll: 'הכול מותר', blocked: 'חסום',
    updTitle: 'עדכון רשימות השירים', updHint: 'מוסיף עוד שירים מוכרים מ־Wikidata. הם נשמרים במכשיר הזה והרשימה רק גדלה.',
    updRun: 'לעדכן עכשיו', updAgain: 'לעדכן שוב', cancel: 'ביטול', back: 'חזרה',
    updDone: (n) => (n ? `+${n} שירים חדשים` : 'אין שירים חדשים הפעם'), updErr: 'אין גישה ל־Wikidata. בדקו את החיבור לאינטרנט ונסו שוב.',
    updLast: (d) => `עודכן לאחרונה ${d}`, updNever: 'עוד לא עודכן', updCount: (b, x) => `${b} מובנים · ${x} שהורדו`,
    updBusy: (what) => `מוריד ${what}…`, updDecade: (d) => `את שנות ה־${String(d).slice(2)}`, updHe: 'שירים בעברית', updIl: 'שירים ישראליים', updWorld: 'להיטים מהעולם',
    hitster: 'HITSTER!', challengeQ: 'מישהו חושב שזה לא במקום?', challengeHint: 'הקישו על השם שלכם ושימו אסימון במקום הנכון',
    reveal: 'חשיפה', pickGap: (n) => `${n}: הקישו איפה זה באמת`, tokenNone: 'אין אסימונים',
    stole: (n) => `הקלף עובר ל־${n}!`, challengeLost: 'האתגר נכשל — האסימונים אבדו', buy: 'קניית קלף', bought: 'קניתם קלף!',
    buyNote: '3 אסימונים', named: 'שם + זמר', wrongName: '✕ השם לא נכון', yearQ: 'השנה המדויקת', yearMiss: 'שנה לא נכונה — הקלף אבד',
    nameMiss: 'לא נאמרו שם השיר והזמר — הקלף אבד', cancelChallenge: 'ביטול',
    whosTeam: 'מי בקבוצה?', teamSub: (era, goal) => `${era} · ${goal} קלפים ביחד · 3 טעויות`,
    teamPara: 'בונים ציר זמן אחד ביחד. אסימונים משותפים, שלוש טעויות.', teamHud: 'ציר הזמן של הקבוצה', everyone: 'כולם יכולים לעזור!',
    teamWin: 'הצלחתם — ביחד!', teamWinNote: (k, t) => `${k} קלפים, ${t === 1 ? 'נשאר אסימון אחד' : `נשארו ${t} אסימונים`}.`, teamNote: (k) => `הקבוצה בנתה ציר זמן של ${k} קלפים.`,
    teamOf: (n, goal, h) => `${n} מתוך ${goal} קלפים  ·  ${h}`,
    bingoSub: (era) => `${era} · הראשון שמשלים שורה`, bingoPara: 'השלימו שורה בכרטיס — בכמה שירים תצליחו?',
    round: (n) => `סיבוב ${n}`, tapSpin: 'הקישו על הגלגל כדי לסובב', spinning: 'מסתובב…', answerNow: 'לענות', listen: 'הקשיבו וחשבו…',
    yourAnswer: (n) => `${n}, התשובה שלך`, lock: 'נעילה', solo1: 'זמר/ת סולו', group1: 'להקה / הרכב', before: 'לפני 2000', after: '2000 ואחרי',
    sayIt: 'אמרו את זה בקול — ואז חשיפה!', whoRight: 'מי צדק?', markBox: (n) => `${n}: סמנו משבצת`, markSolo: 'סמנו משבצת',
    noFree: (n) => `${n}: אין משבצת פנויה בצבע הזה`, line: 'שורה!', bingoWin: (n) => `בינגו ל־${n}!`, bingoSolo: 'בינגו!',
    bingoNote: (n) => (n === 1 ? 'שורה אחרי שיר אחד.' : `שורה אחרי ${n} שירים.`), tieBreak: 'שובר שוויון: מי שצודק לבד ראשון מנצח', tieShort: 'תיקו!',
    nobody: 'אף אחד לא צדק הפעם', okN: (n) => `${n} צדקו`, yourCard: 'הכרטיס שלך', crosses: (n) => `${n} מסומנות`,
    catGroup: 'סולו או להקה?', catB2000: 'לפני 2000?', catY4: '± 4 שנים', catDecade: 'עשור', catY2: '± 2 שנים',
    catTitle: 'שם השיר', catExact: 'השנה המדויקת', catArtist: 'הזמר / הלהקה', catY3: '± 3 שנים',
    qGroup: 'זמר/ת סולו או להקה?', qB2000: 'יצא לפני 2000?', qY: (n) => `השנה — בטווח של ${n} שנים`, qDecade: 'איזה עשור?',
    qTitle: 'איך קוראים לשיר?', qExact: 'השנה המדויקת', qArtist: 'מי שר?', decadeName: (d) => `ה־${String(d).slice(2)}`,
    answerWas: 'התשובה', yourN: (n) => `${n}`,
    shGroup: 'סולו/להקה', shB2000: '< 2000', shY4: '± 4', shDecade: 'עשור', shY2: '± 2', shTitle: 'שם השיר', shYear: 'שנה', shArtist: 'זמר', shY3: '± 3',
    spinBtn: 'סובבו', soloS: 'סולו', groupS: 'להקה', beforeS: 'לפני 2000', afterS: 'מ־2000', passHint: 'עונים ומעבירים את המסך הלאה', continue: 'המשך', tapBox: 'הקישו על משבצת זוהרת',
  },
};
/** A text in Hitster's language (functions get the arguments). */
export function tr(k, ...a) { const v = TXT[hitsterLang()][k] ?? TXT.en[k]; return typeof v === 'function' ? v(...a) : v; }
/** A genre's / song language's name in Hitster's language. */
export const nameOf = (x) => (x ? x[hitsterLang()] || x.en : '');
