// Hit Timeline — the song deck. Well-known songs with the year they were ORIGINALLY released
// (first single or album that carried this recording). { t: title, a: artist, y: year } plus, for songs
// whose title is in another script, ta / aa: the title and artist as Latin-script services may list them.
// Songs with a disputed year (a late-December single that charted the next year, a re-recording
// that became the famous version, a B-side that became a hit years later…) were left out on purpose,
// so a correct guess never depends on trivia about release dates.
// The Demo music service has no real songs, so it gets its own deck: its fictional tracks and their years.

export const SONGS = [
  // ---------------------------------------------------------------- before 1950
  { t: 'Over the Rainbow', a: 'Judy Garland', y: 1939 },
  { t: 'In the Mood', a: 'Glenn Miller', y: 1939 },
  { t: 'Strange Fruit', a: 'Billie Holiday', y: 1939 },
  { t: 'White Christmas', a: 'Bing Crosby', y: 1942 },
  { t: 'La vie en rose', a: 'Édith Piaf', y: 1947 },

  // ---------------------------------------------------------------- 1950s
  { t: 'Unforgettable', a: 'Nat King Cole', y: 1951 },
  { t: "That's Amore", a: 'Dean Martin', y: 1953 },
  { t: 'Rock Around the Clock', a: 'Bill Haley & His Comets', y: 1954 },
  { t: 'Sh-Boom', a: 'The Chords', y: 1954 },
  { t: 'Tutti Frutti', a: 'Little Richard', y: 1955 },
  { t: 'Maybellene', a: 'Chuck Berry', y: 1955 },
  { t: "Ain't That a Shame", a: 'Fats Domino', y: 1955 },
  { t: 'Only You (And You Alone)', a: 'The Platters', y: 1955 },
  { t: 'Heartbreak Hotel', a: 'Elvis Presley', y: 1956 },
  { t: 'Hound Dog', a: 'Elvis Presley', y: 1956 },
  { t: 'Blue Suede Shoes', a: 'Carl Perkins', y: 1956 },
  { t: 'Be-Bop-A-Lula', a: 'Gene Vincent', y: 1956 },
  { t: 'I Walk the Line', a: 'Johnny Cash', y: 1956 },
  { t: 'Que Sera, Sera', a: 'Doris Day', y: 1956 },
  { t: 'Long Tall Sally', a: 'Little Richard', y: 1956 },
  { t: 'Blueberry Hill', a: 'Fats Domino', y: 1956 },
  { t: 'Jailhouse Rock', a: 'Elvis Presley', y: 1957 },
  { t: "That'll Be the Day", a: 'The Crickets', y: 1957 },
  { t: 'Peggy Sue', a: 'Buddy Holly', y: 1957 },
  { t: 'Great Balls of Fire', a: 'Jerry Lee Lewis', y: 1957 },
  { t: 'Wake Up Little Susie', a: 'The Everly Brothers', y: 1957 },
  { t: 'Diana', a: 'Paul Anka', y: 1957 },
  { t: 'Johnny B. Goode', a: 'Chuck Berry', y: 1958 },
  { t: 'La Bamba', a: 'Ritchie Valens', y: 1958 },
  { t: 'Summertime Blues', a: 'Eddie Cochran', y: 1958 },
  { t: 'Yakety Yak', a: 'The Coasters', y: 1958 },
  { t: 'Nel blu, dipinto di blu', a: 'Domenico Modugno', y: 1958 },
  { t: 'Fever', a: 'Peggy Lee', y: 1958 },
  { t: 'All I Have to Do Is Dream', a: 'The Everly Brothers', y: 1958 },
  { t: 'Splish Splash', a: 'Bobby Darin', y: 1958 },
  { t: 'Rockin\' Robin', a: 'Bobby Day', y: 1958 },
  { t: 'Mack the Knife', a: 'Bobby Darin', y: 1959 },
  { t: "What'd I Say", a: 'Ray Charles', y: 1959 },
  { t: 'Put Your Head on My Shoulder', a: 'Paul Anka', y: 1959 },
  { t: 'Shout', a: 'The Isley Brothers', y: 1959 },
  { t: 'Take Five', a: 'The Dave Brubeck Quartet', y: 1959 },

  // ---------------------------------------------------------------- 1960s
  { t: 'Non, je ne regrette rien', a: 'Édith Piaf', y: 1960 },
  { t: "It's Now or Never", a: 'Elvis Presley', y: 1960 },
  { t: 'Georgia on My Mind', a: 'Ray Charles', y: 1960 },
  { t: 'The Twist', a: 'Chubby Checker', y: 1960 },
  { t: 'Only the Lonely', a: 'Roy Orbison', y: 1960 },
  { t: 'Stand by Me', a: 'Ben E. King', y: 1961 },
  { t: 'Hit the Road Jack', a: 'Ray Charles', y: 1961 },
  { t: "Can't Help Falling in Love", a: 'Elvis Presley', y: 1961 },
  { t: 'Crazy', a: 'Patsy Cline', y: 1961 },
  { t: 'Runaway', a: 'Del Shannon', y: 1961 },
  { t: 'The Lion Sleeps Tonight', a: 'The Tokens', y: 1961 },
  { t: 'Sukiyaki', a: 'Kyu Sakamoto', y: 1961, ta: '上を向いて歩こう', aa: '坂本九' },
  { t: 'Twist and Shout', a: 'The Isley Brothers', y: 1962 },
  { t: 'Love Me Do', a: 'The Beatles', y: 1962 },
  { t: 'Green Onions', a: "Booker T. & the M.G.'s", y: 1962 },
  { t: 'The Loco-Motion', a: 'Little Eva', y: 1962 },
  { t: "Big Girls Don't Cry", a: 'The Four Seasons', y: 1962 },
  { t: 'Surfin\' Safari', a: 'The Beach Boys', y: 1962 },
  { t: 'She Loves You', a: 'The Beatles', y: 1963 },
  { t: 'Be My Baby', a: 'The Ronettes', y: 1963 },
  { t: 'Ring of Fire', a: 'Johnny Cash', y: 1963 },
  { t: 'Louie Louie', a: 'The Kingsmen', y: 1963 },
  { t: 'Blowin\' in the Wind', a: 'Bob Dylan', y: 1963 },
  { t: 'Oh, Pretty Woman', a: 'Roy Orbison', y: 1964 },
  { t: 'The House of the Rising Sun', a: 'The Animals', y: 1964 },
  { t: 'Baby Love', a: 'The Supremes', y: 1964 },
  { t: 'You Really Got Me', a: 'The Kinks', y: 1964 },
  { t: "A Hard Day's Night", a: 'The Beatles', y: 1964 },
  { t: 'My Guy', a: 'Mary Wells', y: 1964 },
  { t: 'Dancing in the Street', a: 'Martha and the Vandellas', y: 1964 },
  { t: 'The Girl from Ipanema', a: 'Stan Getz & João Gilberto', y: 1964 },
  { t: 'Downtown', a: 'Petula Clark', y: 1964 },
  { t: 'Fly Me to the Moon', a: 'Frank Sinatra', y: 1964 },
  { t: "(I Can't Get No) Satisfaction", a: 'The Rolling Stones', y: 1965 },
  { t: 'Yesterday', a: 'The Beatles', y: 1965 },
  { t: 'Like a Rolling Stone', a: 'Bob Dylan', y: 1965 },
  { t: 'I Got You (I Feel Good)', a: 'James Brown', y: 1965 },
  { t: 'Mr. Tambourine Man', a: 'The Byrds', y: 1965 },
  { t: 'Unchained Melody', a: 'The Righteous Brothers', y: 1965 },
  { t: 'My Generation', a: 'The Who', y: 1965 },
  { t: 'In the Midnight Hour', a: 'Wilson Pickett', y: 1965 },
  { t: 'Good Vibrations', a: 'The Beach Boys', y: 1966 },
  { t: 'Paint It Black', a: 'The Rolling Stones', y: 1966 },
  { t: 'River Deep – Mountain High', a: 'Ike & Tina Turner', y: 1966 },
  { t: "Reach Out I'll Be There", a: 'Four Tops', y: 1966 },
  { t: 'Sunny', a: 'Bobby Hebb', y: 1966 },
  { t: "I'm a Believer", a: 'The Monkees', y: 1966 },
  { t: 'Strangers in the Night', a: 'Frank Sinatra', y: 1966 },
  { t: 'Wild Thing', a: 'The Troggs', y: 1966 },
  { t: 'Respect', a: 'Aretha Franklin', y: 1967 },
  { t: 'Light My Fire', a: 'The Doors', y: 1967 },
  { t: 'Somebody to Love', a: 'Jefferson Airplane', y: 1967 },
  { t: 'Happy Together', a: 'The Turtles', y: 1967 },
  { t: "Ain't No Mountain High Enough", a: 'Marvin Gaye & Tammi Terrell', y: 1967 },
  { t: 'What a Wonderful World', a: 'Louis Armstrong', y: 1967 },
  { t: 'Purple Haze', a: 'The Jimi Hendrix Experience', y: 1967 },
  { t: 'A Whiter Shade of Pale', a: 'Procol Harum', y: 1967 },
  { t: 'Brown Eyed Girl', a: 'Van Morrison', y: 1967 },
  { t: 'All You Need Is Love', a: 'The Beatles', y: 1967 },
  { t: 'Pata Pata', a: 'Miriam Makeba', y: 1967 },
  { t: 'San Francisco (Be Sure to Wear Flowers in Your Hair)', a: 'Scott McKenzie', y: 1967 },
  { t: 'ירושלים של זהב', a: 'שולי נתן', y: 1967, ta: 'Yerushalayim Shel Zahav', aa: 'Shuli Natan' },
  { t: 'Hey Jude', a: 'The Beatles', y: 1968 },
  { t: "(Sittin' On) The Dock of the Bay", a: 'Otis Redding', y: 1968 },
  { t: 'I Heard It Through the Grapevine', a: 'Marvin Gaye', y: 1968 },
  { t: 'Born to Be Wild', a: 'Steppenwolf', y: 1968 },
  { t: 'Mrs. Robinson', a: 'Simon & Garfunkel', y: 1968 },
  { t: 'Sympathy for the Devil', a: 'The Rolling Stones', y: 1968 },
  { t: 'Son of a Preacher Man', a: 'Dusty Springfield', y: 1968 },
  { t: 'Here Comes the Sun', a: 'The Beatles', y: 1969 },
  { t: 'Space Oddity', a: 'David Bowie', y: 1969 },
  { t: 'Sugar, Sugar', a: 'The Archies', y: 1969 },
  { t: 'Bad Moon Rising', a: 'Creedence Clearwater Revival', y: 1969 },
  { t: "Je t'aime… moi non plus", a: 'Jane Birkin & Serge Gainsbourg', y: 1969 },
  { t: 'Whole Lotta Love', a: 'Led Zeppelin', y: 1969 },
  { t: 'Aquarius / Let the Sunshine In', a: 'The 5th Dimension', y: 1969 },
  { t: 'שיר לשלום', a: 'להקת הנח"ל', y: 1969, ta: 'Shir LaShalom', aa: 'Lehakat HaNahal' },

  // ---------------------------------------------------------------- 1970s
  { t: 'Let It Be', a: 'The Beatles', y: 1970 },
  { t: 'Bridge over Troubled Water', a: 'Simon & Garfunkel', y: 1970 },
  { t: 'ABC', a: 'The Jackson 5', y: 1970 },
  { t: 'Lola', a: 'The Kinks', y: 1970 },
  { t: 'Paranoid', a: 'Black Sabbath', y: 1970 },
  { t: 'Your Song', a: 'Elton John', y: 1970 },
  { t: 'War', a: 'Edwin Starr', y: 1970 },
  { t: 'Layla', a: 'Derek and the Dominos', y: 1970 },
  { t: 'Imagine', a: 'John Lennon', y: 1971 },
  { t: 'Stairway to Heaven', a: 'Led Zeppelin', y: 1971 },
  { t: "What's Going On", a: 'Marvin Gaye', y: 1971 },
  { t: 'Take Me Home, Country Roads', a: 'John Denver', y: 1971 },
  { t: 'American Pie', a: 'Don McLean', y: 1971 },
  { t: 'Riders on the Storm', a: 'The Doors', y: 1971 },
  { t: 'Brown Sugar', a: 'The Rolling Stones', y: 1971 },
  { t: "Let's Stay Together", a: 'Al Green', y: 1971 },
  { t: 'Superstition', a: 'Stevie Wonder', y: 1972 },
  { t: 'Lean on Me', a: 'Bill Withers', y: 1972 },
  { t: 'Rocket Man', a: 'Elton John', y: 1972 },
  { t: 'Heart of Gold', a: 'Neil Young', y: 1972 },
  { t: 'Walk on the Wild Side', a: 'Lou Reed', y: 1972 },
  { t: 'Smoke on the Water', a: 'Deep Purple', y: 1972 },
  { t: "School's Out", a: 'Alice Cooper', y: 1972 },
  { t: 'Piano Man', a: 'Billy Joel', y: 1973 },
  { t: 'Money', a: 'Pink Floyd', y: 1973 },
  { t: 'Killing Me Softly with His Song', a: 'Roberta Flack', y: 1973 },
  { t: 'Live and Let Die', a: 'Wings', y: 1973 },
  { t: 'Sweet Home Alabama', a: 'Lynyrd Skynyrd', y: 1974 },
  { t: 'Waterloo', a: 'ABBA', y: 1974 },
  { t: 'Kung Fu Fighting', a: 'Carl Douglas', y: 1974 },
  { t: 'Rock Your Baby', a: 'George McCrae', y: 1974 },
  { t: 'Lady Marmalade', a: 'Labelle', y: 1974 },
  { t: 'Rebel Rebel', a: 'David Bowie', y: 1974 },
  { t: "You're the First, the Last, My Everything", a: 'Barry White', y: 1974 },
  { t: 'נתתי לה חיי', a: 'כוורת', y: 1974, ta: 'Natati La Chayai', aa: 'Kaveret' },
  { t: 'Bohemian Rhapsody', a: 'Queen', y: 1975 },
  { t: 'Born to Run', a: 'Bruce Springsteen', y: 1975 },
  { t: 'Wish You Were Here', a: 'Pink Floyd', y: 1975 },
  { t: 'The Hustle', a: 'Van McCoy', y: 1975 },
  { t: 'Love Will Keep Us Together', a: 'Captain & Tennille', y: 1975 },
  { t: 'Mamma Mia', a: 'ABBA', y: 1975 },
  { t: 'Rhinestone Cowboy', a: 'Glen Campbell', y: 1975 },
  { t: 'Fly, Robin, Fly', a: 'Silver Convention', y: 1975 },
  { t: 'Dancing Queen', a: 'ABBA', y: 1976 },
  { t: 'Hotel California', a: 'Eagles', y: 1976 },
  { t: "Don't Go Breaking My Heart", a: 'Elton John & Kiki Dee', y: 1976 },
  { t: 'Blitzkrieg Bop', a: 'Ramones', y: 1976 },
  { t: 'More Than a Feeling', a: 'Boston', y: 1976 },
  { t: 'Car Wash', a: 'Rose Royce', y: 1976 },
  { t: 'Daddy Cool', a: 'Boney M.', y: 1976 },
  { t: 'Play That Funky Music', a: 'Wild Cherry', y: 1976 },
  { t: 'If You Leave Me Now', a: 'Chicago', y: 1976 },
  { t: "Stayin' Alive", a: 'Bee Gees', y: 1977 },
  { t: 'We Will Rock You', a: 'Queen', y: 1977 },
  { t: 'Dreams', a: 'Fleetwood Mac', y: 1977 },
  { t: 'I Feel Love', a: 'Donna Summer', y: 1977 },
  { t: '"Heroes"', a: 'David Bowie', y: 1977 },
  { t: 'God Save the Queen', a: 'Sex Pistols', y: 1977 },
  { t: 'Barracuda', a: 'Heart', y: 1977 },
  { t: 'Lovely Day', a: 'Bill Withers', y: 1977 },
  { t: 'Le Freak', a: 'Chic', y: 1978 },
  { t: 'Y.M.C.A.', a: 'Village People', y: 1978 },
  { t: 'I Will Survive', a: 'Gloria Gaynor', y: 1978 },
  { t: 'Wuthering Heights', a: 'Kate Bush', y: 1978 },
  { t: 'A-Ba-Ni-Bi', a: 'Izhar Cohen & Alphabeta', y: 1978 },
  { t: 'Sultans of Swing', a: 'Dire Straits', y: 1978 },
  { t: 'September', a: 'Earth, Wind & Fire', y: 1978 },
  { t: 'Hopelessly Devoted to You', a: 'Olivia Newton-John', y: 1978 },
  { t: "You're the One That I Want", a: 'John Travolta & Olivia Newton-John', y: 1978 },
  { t: 'Roxanne', a: 'The Police', y: 1978 },
  { t: 'Another Brick in the Wall, Part 2', a: 'Pink Floyd', y: 1979 },
  { t: 'Hallelujah', a: 'Gali Atari & Milk and Honey', y: 1979 },
  { t: "Don't Stop 'Til You Get Enough", a: 'Michael Jackson', y: 1979 },
  { t: 'Video Killed the Radio Star', a: 'The Buggles', y: 1979 },
  { t: 'Highway to Hell', a: 'AC/DC', y: 1979 },
  { t: 'London Calling', a: 'The Clash', y: 1979 },
  { t: "Rapper's Delight", a: 'The Sugarhill Gang', y: 1979 },
  { t: 'Ring My Bell', a: 'Anita Ward', y: 1979 },
  { t: 'My Sharona', a: 'The Knack', y: 1979 },
  { t: 'Pop Muzik', a: 'M', y: 1979 },

  // ---------------------------------------------------------------- 1980s
  { t: 'Another One Bites the Dust', a: 'Queen', y: 1980 },
  { t: 'Back in Black', a: 'AC/DC', y: 1980 },
  { t: 'Call Me', a: 'Blondie', y: 1980 },
  { t: 'Celebration', a: 'Kool & the Gang', y: 1980 },
  { t: 'Upside Down', a: 'Diana Ross', y: 1980 },
  { t: 'Super Trouper', a: 'ABBA', y: 1980 },
  { t: 'Love Will Tear Us Apart', a: 'Joy Division', y: 1980 },
  { t: 'Tainted Love', a: 'Soft Cell', y: 1981 },
  { t: "Don't Stop Believin'", a: 'Journey', y: 1981 },
  { t: 'Bette Davis Eyes', a: 'Kim Carnes', y: 1981 },
  { t: 'Physical', a: 'Olivia Newton-John', y: 1981 },
  { t: "Don't You Want Me", a: 'The Human League', y: 1981 },
  { t: "Jessie's Girl", a: 'Rick Springfield', y: 1981 },
  { t: 'Under Pressure', a: 'Queen & David Bowie', y: 1981 },
  { t: 'Billie Jean', a: 'Michael Jackson', y: 1982 },
  { t: 'Eye of the Tiger', a: 'Survivor', y: 1982 },
  { t: 'Africa', a: 'Toto', y: 1982 },
  { t: 'Come On Eileen', a: 'Dexys Midnight Runners', y: 1982 },
  { t: 'Sexual Healing', a: 'Marvin Gaye', y: 1982 },
  { t: 'Da Da Da', a: 'Trio', y: 1982 },
  { t: 'Felicità', a: 'Al Bano & Romina Power', y: 1982 },
  { t: 'Every Breath You Take', a: 'The Police', y: 1983 },
  { t: 'Sweet Dreams (Are Made of This)', a: 'Eurythmics', y: 1983 },
  { t: '99 Luftballons', a: 'Nena', y: 1983 },
  { t: 'Girls Just Want to Have Fun', a: 'Cyndi Lauper', y: 1983 },
  { t: 'Total Eclipse of the Heart', a: 'Bonnie Tyler', y: 1983 },
  { t: 'Blue Monday', a: 'New Order', y: 1983 },
  { t: 'Karma Chameleon', a: 'Culture Club', y: 1983 },
  { t: "Let's Dance", a: 'David Bowie', y: 1983 },
  { t: 'Relax', a: 'Frankie Goes to Hollywood', y: 1983 },
  { t: 'חי', a: 'עפרה חזה', y: 1983, ta: 'Chai', aa: 'Ofra Haza' },
  { t: 'When Doves Cry', a: 'Prince', y: 1984 },
  { t: 'Like a Virgin', a: 'Madonna', y: 1984 },
  { t: 'Wake Me Up Before You Go-Go', a: 'Wham!', y: 1984 },
  { t: 'Footloose', a: 'Kenny Loggins', y: 1984 },
  { t: 'Ghostbusters', a: 'Ray Parker Jr.', y: 1984 },
  { t: 'Born in the U.S.A.', a: 'Bruce Springsteen', y: 1984 },
  { t: 'I Just Called to Say I Love You', a: 'Stevie Wonder', y: 1984 },
  { t: 'Self Control', a: 'Laura Branigan', y: 1984 },
  { t: 'Smalltown Boy', a: 'Bronski Beat', y: 1984 },
  { t: 'Careless Whisper', a: 'George Michael', y: 1984 },
  { t: 'You Spin Me Round (Like a Record)', a: 'Dead or Alive', y: 1984 },
  { t: 'Take On Me', a: 'a-ha', y: 1985 },
  { t: "Don't You (Forget About Me)", a: 'Simple Minds', y: 1985 },
  { t: 'Money for Nothing', a: 'Dire Straits', y: 1985 },
  { t: 'Rock Me Amadeus', a: 'Falco', y: 1985 },
  { t: 'We Are the World', a: 'USA for Africa', y: 1985 },
  { t: 'Everybody Wants to Rule the World', a: 'Tears for Fears', y: 1985 },
  { t: 'Running Up That Hill (A Deal with God)', a: 'Kate Bush', y: 1985 },
  { t: 'The Power of Love', a: 'Huey Lewis and the News', y: 1985 },
  { t: "Livin' on a Prayer", a: 'Bon Jovi', y: 1986 },
  { t: 'The Final Countdown', a: 'Europe', y: 1986 },
  { t: 'Walk Like an Egyptian', a: 'The Bangles', y: 1986 },
  { t: 'Sledgehammer', a: 'Peter Gabriel', y: 1986 },
  { t: 'Take My Breath Away', a: 'Berlin', y: 1986 },
  { t: 'Kiss', a: 'Prince', y: 1986 },
  { t: 'Danger Zone', a: 'Kenny Loggins', y: 1986 },
  { t: 'Venus', a: 'Bananarama', y: 1986 },
  { t: 'Higher Love', a: 'Steve Winwood', y: 1986 },
  { t: 'Never Gonna Give You Up', a: 'Rick Astley', y: 1987 },
  { t: 'With or Without You', a: 'U2', y: 1987 },
  { t: "Sweet Child o' Mine", a: "Guns N' Roses", y: 1987 },
  { t: 'I Wanna Dance with Somebody (Who Loves Me)', a: 'Whitney Houston', y: 1987 },
  { t: 'Bamboléo', a: 'Gipsy Kings', y: 1987 },
  { t: "Ella, elle l'a", a: 'France Gall', y: 1987 },
  { t: 'Pump Up the Volume', a: 'MARRS', y: 1987 },
  { t: 'Need You Tonight', a: 'INXS', y: 1987 },
  { t: "It's a Sin", a: 'Pet Shop Boys', y: 1987 },
  { t: "Don't Worry, Be Happy", a: 'Bobby McFerrin', y: 1988 },
  { t: 'Fast Car', a: 'Tracy Chapman', y: 1988 },
  { t: 'Orinoco Flow', a: 'Enya', y: 1988 },
  { t: 'Buffalo Stance', a: 'Neneh Cherry', y: 1988 },
  { t: 'The Only Way Is Up', a: 'Yazz', y: 1988 },
  { t: 'Kokomo', a: 'The Beach Boys', y: 1988 },
  { t: 'Like a Prayer', a: 'Madonna', y: 1989 },
  { t: 'Lambada', a: 'Kaoma', y: 1989 },
  { t: 'Pump Up the Jam', a: 'Technotronic', y: 1989 },
  { t: 'Love Shack', a: "The B-52's", y: 1989 },
  { t: 'Another Day in Paradise', a: 'Phil Collins', y: 1989 },
  { t: "Free Fallin'", a: 'Tom Petty', y: 1989 },
  { t: 'Bust a Move', a: 'Young MC', y: 1989 },

  // ---------------------------------------------------------------- 1990s
  { t: 'Vogue', a: 'Madonna', y: 1990 },
  { t: 'Nothing Compares 2 U', a: "Sinéad O'Connor", y: 1990 },
  { t: "U Can't Touch This", a: 'MC Hammer', y: 1990 },
  { t: 'Enjoy the Silence', a: 'Depeche Mode', y: 1990 },
  { t: 'Thunderstruck', a: 'AC/DC', y: 1990 },
  { t: 'Unbelievable', a: 'EMF', y: 1990 },
  { t: 'Wind of Change', a: 'Scorpions', y: 1990 },
  { t: 'Poison', a: 'Bell Biv DeVoe', y: 1990 },
  { t: 'Smells Like Teen Spirit', a: 'Nirvana', y: 1991 },
  { t: 'Losing My Religion', a: 'R.E.M.', y: 1991 },
  { t: '(Everything I Do) I Do It for You', a: 'Bryan Adams', y: 1991 },
  { t: 'Black or White', a: 'Michael Jackson', y: 1991 },
  { t: 'Enter Sandman', a: 'Metallica', y: 1991 },
  { t: 'Give It Away', a: 'Red Hot Chili Peppers', y: 1991 },
  { t: "I'm Too Sexy", a: 'Right Said Fred', y: 1991 },
  { t: 'Summertime', a: 'DJ Jazzy Jeff & The Fresh Prince', y: 1991 },
  { t: 'I Will Always Love You', a: 'Whitney Houston', y: 1992 },
  { t: 'Jump', a: 'Kris Kross', y: 1992 },
  { t: 'Rhythm Is a Dancer', a: 'Snap!', y: 1992 },
  { t: 'Killing in the Name', a: 'Rage Against the Machine', y: 1992 },
  { t: 'Creep', a: 'Radiohead', y: 1992 },
  { t: 'Achy Breaky Heart', a: 'Billy Ray Cyrus', y: 1992 },
  { t: 'Baby Got Back', a: 'Sir Mix-a-Lot', y: 1992 },
  { t: 'End of the Road', a: 'Boyz II Men', y: 1992 },
  { t: 'What Is Love', a: 'Haddaway', y: 1993 },
  { t: 'The Sign', a: 'Ace of Base', y: 1993 },
  { t: 'Mr. Vain', a: 'Culture Beat', y: 1993 },
  { t: "I'd Do Anything for Love (But I Won't Do That)", a: 'Meat Loaf', y: 1993 },
  { t: 'No Limit', a: '2 Unlimited', y: 1993 },
  { t: 'Mr. Jones', a: 'Counting Crows', y: 1993 },
  { t: 'Loser', a: 'Beck', y: 1993 },
  { t: 'Zombie', a: 'The Cranberries', y: 1994 },
  { t: 'Basket Case', a: 'Green Day', y: 1994 },
  { t: 'Love Is All Around', a: 'Wet Wet Wet', y: 1994 },
  { t: 'Cotton Eye Joe', a: 'Rednex', y: 1994 },
  { t: 'Black Hole Sun', a: 'Soundgarden', y: 1994 },
  { t: 'Stay (I Missed You)', a: 'Lisa Loeb', y: 1994 },
  { t: 'Sabotage', a: 'Beastie Boys', y: 1994 },
  { t: 'Waterfalls', a: 'TLC', y: 1995 },
  { t: "Gangsta's Paradise", a: 'Coolio', y: 1995 },
  { t: 'Wonderwall', a: 'Oasis', y: 1995 },
  { t: 'You Oughta Know', a: 'Alanis Morissette', y: 1995 },
  { t: 'Boombastic', a: 'Shaggy', y: 1995 },
  { t: 'Fantasy', a: 'Mariah Carey', y: 1995 },
  { t: 'Common People', a: 'Pulp', y: 1995 },
  { t: 'Back for Good', a: 'Take That', y: 1995 },
  { t: 'Wannabe', a: 'Spice Girls', y: 1996 },
  { t: 'Killing Me Softly', a: 'Fugees', y: 1996 },
  { t: 'Firestarter', a: 'The Prodigy', y: 1996 },
  { t: 'No Diggity', a: 'Blackstreet', y: 1996 },
  { t: 'Virtual Insanity', a: 'Jamiroquai', y: 1996 },
  { t: 'Return of the Mack', a: 'Mark Morrison', y: 1996 },
  { t: 'Barbie Girl', a: 'Aqua', y: 1997 },
  { t: 'My Heart Will Go On', a: 'Céline Dion', y: 1997 },
  { t: 'Bitter Sweet Symphony', a: 'The Verve', y: 1997 },
  { t: 'MMMBop', a: 'Hanson', y: 1997 },
  { t: 'Tubthumping', a: 'Chumbawamba', y: 1997 },
  { t: 'Du hast', a: 'Rammstein', y: 1997 },
  { t: 'Around the World', a: 'Daft Punk', y: 1997 },
  { t: 'Men in Black', a: 'Will Smith', y: 1997 },
  { t: 'Torn', a: 'Natalie Imbruglia', y: 1997 },
  { t: 'Song 2', a: 'Blur', y: 1997 },
  { t: '...Baby One More Time', a: 'Britney Spears', y: 1998 },
  { t: 'Believe', a: 'Cher', y: 1998 },
  { t: 'Diva', a: 'Dana International', y: 1998 },
  { t: 'Iris', a: 'Goo Goo Dolls', y: 1998 },
  { t: 'Blue (Da Ba Dee)', a: 'Eiffel 65', y: 1998 },
  { t: 'The Boy Is Mine', a: 'Brandy & Monica', y: 1998 },
  { t: 'Doo Wop (That Thing)', a: 'Lauryn Hill', y: 1998 },
  { t: "Livin' la Vida Loca", a: 'Ricky Martin', y: 1999 },
  { t: 'Mambo No. 5 (A Little Bit of...)', a: 'Lou Bega', y: 1999 },
  { t: 'Smooth', a: 'Santana feat. Rob Thomas', y: 1999 },
  { t: 'All Star', a: 'Smash Mouth', y: 1999 },
  { t: 'Genie in a Bottle', a: 'Christina Aguilera', y: 1999 },
  { t: 'I Want It That Way', a: 'Backstreet Boys', y: 1999 },
  { t: 'My Name Is', a: 'Eminem', y: 1999 },
  { t: 'Sandstorm', a: 'Darude', y: 1999 },

  // ---------------------------------------------------------------- 2000s
  { t: 'Oops!... I Did It Again', a: 'Britney Spears', y: 2000 },
  { t: 'Yellow', a: 'Coldplay', y: 2000 },
  { t: 'In the End', a: 'Linkin Park', y: 2000 },
  { t: 'Bye Bye Bye', a: '*NSYNC', y: 2000 },
  { t: "It's My Life", a: 'Bon Jovi', y: 2000 },
  { t: 'Beautiful Day', a: 'U2', y: 2000 },
  { t: 'Ms. Jackson', a: 'OutKast', y: 2000 },
  { t: 'Rock DJ', a: 'Robbie Williams', y: 2000 },
  { t: 'Who Let the Dogs Out', a: 'Baha Men', y: 2000 },
  { t: "Can't Get You Out of My Head", a: 'Kylie Minogue', y: 2001 },
  { t: 'Clint Eastwood', a: 'Gorillaz', y: 2001 },
  { t: "Fallin'", a: 'Alicia Keys', y: 2001 },
  { t: 'Get Ur Freak On', a: 'Missy Elliott', y: 2001 },
  { t: 'Chop Suey!', a: 'System of a Down', y: 2001 },
  { t: 'Whenever, Wherever', a: 'Shakira', y: 2001 },
  { t: 'Family Affair', a: 'Mary J. Blige', y: 2001 },
  { t: 'How You Remind Me', a: 'Nickelback', y: 2001 },
  { t: 'Lose Yourself', a: 'Eminem', y: 2002 },
  { t: 'Complicated', a: 'Avril Lavigne', y: 2002 },
  { t: 'Hot in Herre', a: 'Nelly', y: 2002 },
  { t: 'Aserejé', a: 'Las Ketchup', y: 2002 },
  { t: 'Cry Me a River', a: 'Justin Timberlake', y: 2002 },
  { t: 'A Thousand Miles', a: 'Vanessa Carlton', y: 2002 },
  { t: 'Crazy in Love', a: 'Beyoncé', y: 2003 },
  { t: 'Hey Ya!', a: 'OutKast', y: 2003 },
  { t: 'Seven Nation Army', a: 'The White Stripes', y: 2003 },
  { t: 'In da Club', a: '50 Cent', y: 2003 },
  { t: 'Dragostea din tei', a: 'O-Zone', y: 2003 },
  { t: 'Toxic', a: 'Britney Spears', y: 2003 },
  { t: 'Where Is the Love?', a: 'The Black Eyed Peas', y: 2003 },
  { t: 'Numb', a: 'Linkin Park', y: 2003 },
  { t: 'Mr. Brightside', a: 'The Killers', y: 2003 },
  { t: 'Yeah!', a: 'Usher', y: 2004 },
  { t: 'Gasolina', a: 'Daddy Yankee', y: 2004 },
  { t: 'Take Me Out', a: 'Franz Ferdinand', y: 2004 },
  { t: 'Boulevard of Broken Dreams', a: 'Green Day', y: 2004 },
  { t: 'Since U Been Gone', a: 'Kelly Clarkson', y: 2004 },
  { t: 'Gold Digger', a: 'Kanye West', y: 2005 },
  { t: 'Hung Up', a: 'Madonna', y: 2005 },
  { t: 'Bad Day', a: 'Daniel Powter', y: 2005 },
  { t: 'ממעמקים', a: 'הפרויקט של עידן רייכל', y: 2005, ta: "Mima'amakim", aa: 'The Idan Raichel Project' },
  { t: "Hips Don't Lie", a: 'Shakira', y: 2006 },
  { t: 'Crazy', a: 'Gnarls Barkley', y: 2006 },
  { t: 'SexyBack', a: 'Justin Timberlake', y: 2006 },
  { t: 'Chasing Cars', a: 'Snow Patrol', y: 2006 },
  { t: 'Rehab', a: 'Amy Winehouse', y: 2006 },
  { t: 'Maneater', a: 'Nelly Furtado', y: 2006 },
  { t: 'Smile', a: 'Lily Allen', y: 2006 },
  { t: 'Umbrella', a: 'Rihanna', y: 2007 },
  { t: 'Becoming Insane', a: 'Infected Mushroom', y: 2007 },
  { t: 'Ruby', a: 'Kaiser Chiefs', y: 2007 },
  { t: 'Bleeding Love', a: 'Leona Lewis', y: 2007 },
  { t: 'Paper Planes', a: 'M.I.A.', y: 2007 },
  { t: 'Viva la Vida', a: 'Coldplay', y: 2008 },
  { t: 'I Kissed a Girl', a: 'Katy Perry', y: 2008 },
  { t: 'Just Dance', a: 'Lady Gaga', y: 2008 },
  { t: 'Poker Face', a: 'Lady Gaga', y: 2008 },
  { t: 'Single Ladies (Put a Ring on It)', a: 'Beyoncé', y: 2008 },
  { t: 'Sex on Fire', a: 'Kings of Leon', y: 2008 },
  { t: 'Mercy', a: 'Duffy', y: 2008 },
  { t: 'Love Story', a: 'Taylor Swift', y: 2008 },
  { t: 'The Fire in Your Eyes', a: 'Boaz Mauda', y: 2008 },
  { t: 'I Gotta Feeling', a: 'The Black Eyed Peas', y: 2009 },
  { t: 'Empire State of Mind', a: 'Jay-Z & Alicia Keys', y: 2009 },
  { t: 'Party in the U.S.A.', a: 'Miley Cyrus', y: 2009 },
  { t: 'Fireflies', a: 'Owl City', y: 2009 },
  { t: 'TiK ToK', a: 'Kesha', y: 2009 },
  { t: 'Down', a: 'Jay Sean', y: 2009 },
  { t: 'Bad Romance', a: 'Lady Gaga', y: 2009 },

  // ---------------------------------------------------------------- 2010s
  { t: 'Rolling in the Deep', a: 'Adele', y: 2010 },
  { t: 'Waka Waka (This Time for Africa)', a: 'Shakira', y: 2010 },
  { t: 'Danza Kuduro', a: 'Don Omar', y: 2010 },
  { t: 'Firework', a: 'Katy Perry', y: 2010 },
  { t: 'Only Girl (In the World)', a: 'Rihanna', y: 2010 },
  { t: 'Love the Way You Lie', a: 'Eminem feat. Rihanna', y: 2010 },
  { t: 'Dynamite', a: 'Taio Cruz', y: 2010 },
  { t: 'Just the Way You Are', a: 'Bruno Mars', y: 2010 },
  { t: 'Airplanes', a: 'B.o.B feat. Hayley Williams', y: 2010 },
  { t: 'Milim', a: 'Harel Skaat', y: 2010 },
  { t: 'Someone Like You', a: 'Adele', y: 2011 },
  { t: 'Party Rock Anthem', a: 'LMFAO', y: 2011 },
  { t: 'Moves Like Jagger', a: 'Maroon 5', y: 2011 },
  { t: 'Ai Se Eu Te Pego', a: 'Michel Teló', y: 2011 },
  { t: 'Somebody That I Used to Know', a: 'Gotye', y: 2011 },
  { t: 'Titanium', a: 'David Guetta feat. Sia', y: 2011 },
  { t: 'Call Me Maybe', a: 'Carly Rae Jepsen', y: 2011 },
  { t: 'Gangnam Style', a: 'PSY', y: 2012 },
  { t: 'Diamonds', a: 'Rihanna', y: 2012 },
  { t: 'Thrift Shop', a: 'Macklemore & Ryan Lewis', y: 2012 },
  { t: 'Locked Out of Heaven', a: 'Bruno Mars', y: 2012 },
  { t: 'Euphoria', a: 'Loreen', y: 2012 },
  { t: 'I Knew You Were Trouble', a: 'Taylor Swift', y: 2012 },
  { t: 'Skyfall', a: 'Adele', y: 2012 },
  { t: 'Get Lucky', a: 'Daft Punk', y: 2013 },
  { t: 'Wake Me Up', a: 'Avicii', y: 2013 },
  { t: 'Royals', a: 'Lorde', y: 2013 },
  { t: 'Happy', a: 'Pharrell Williams', y: 2013 },
  { t: 'Blurred Lines', a: 'Robin Thicke', y: 2013 },
  { t: 'Counting Stars', a: 'OneRepublic', y: 2013 },
  { t: 'Let It Go', a: 'Idina Menzel', y: 2013 },
  { t: 'Wrecking Ball', a: 'Miley Cyrus', y: 2013 },
  { t: 'Stolen Dance', a: 'Milky Chance', y: 2013 },
  { t: 'Uptown Funk', a: 'Mark Ronson feat. Bruno Mars', y: 2014 },
  { t: 'Shake It Off', a: 'Taylor Swift', y: 2014 },
  { t: 'All About That Bass', a: 'Meghan Trainor', y: 2014 },
  { t: 'Bailando', a: 'Enrique Iglesias', y: 2014 },
  { t: 'Rather Be', a: 'Clean Bandit', y: 2014 },
  { t: 'Stay with Me', a: 'Sam Smith', y: 2014 },
  { t: 'Thinking Out Loud', a: 'Ed Sheeran', y: 2014 },
  { t: 'Chandelier', a: 'Sia', y: 2014 },
  { t: 'Hello', a: 'Adele', y: 2015 },
  { t: 'See You Again', a: 'Wiz Khalifa feat. Charlie Puth', y: 2015 },
  { t: 'Lean On', a: 'Major Lazer & DJ Snake', y: 2015 },
  { t: 'Golden Boy', a: 'Nadav Guedj', y: 2015 },
  { t: 'Sorry', a: 'Justin Bieber', y: 2015 },
  { t: 'Hotline Bling', a: 'Drake', y: 2015 },
  { t: "Can't Feel My Face", a: 'The Weeknd', y: 2015 },
  { t: 'Love Me Like You Do', a: 'Ellie Goulding', y: 2015 },
  { t: 'Faded', a: 'Alan Walker', y: 2015 },
  { t: 'Cheap Thrills', a: 'Sia', y: 2016 },
  { t: 'Closer', a: 'The Chainsmokers', y: 2016 },
  { t: "Can't Stop the Feeling!", a: 'Justin Timberlake', y: 2016 },
  { t: 'This Is What You Came For', a: 'Calvin Harris', y: 2016 },
  { t: 'Heathens', a: 'Twenty One Pilots', y: 2016 },
  { t: 'Despacito', a: 'Luis Fonsi', y: 2017 },
  { t: 'Shape of You', a: 'Ed Sheeran', y: 2017 },
  { t: 'Mi Gente', a: 'J Balvin & Willy William', y: 2017 },
  { t: 'Believer', a: 'Imagine Dragons', y: 2017 },
  { t: 'Havana', a: 'Camila Cabello', y: 2017 },
  { t: 'HUMBLE.', a: 'Kendrick Lamar', y: 2017 },
  { t: 'Something Just Like This', a: 'The Chainsmokers & Coldplay', y: 2017 },
  { t: 'New Rules', a: 'Dua Lipa', y: 2017 },
  { t: 'Toy', a: 'Netta', y: 2018 },
  { t: "God's Plan", a: 'Drake', y: 2018 },
  { t: 'Shallow', a: 'Lady Gaga & Bradley Cooper', y: 2018 },
  { t: 'Sicko Mode', a: 'Travis Scott', y: 2018 },
  { t: 'thank u, next', a: 'Ariana Grande', y: 2018 },
  { t: 'Taki Taki', a: 'DJ Snake', y: 2018 },
  { t: 'One Kiss', a: 'Calvin Harris & Dua Lipa', y: 2018 },
  { t: 'Sweet but Psycho', a: 'Ava Max', y: 2018 },
  { t: 'bad guy', a: 'Billie Eilish', y: 2019 },
  { t: 'Señorita', a: 'Shawn Mendes & Camila Cabello', y: 2019 },
  { t: 'Dance Monkey', a: 'Tones and I', y: 2019 },
  { t: 'Arcade', a: 'Duncan Laurence', y: 2019 },
  { t: 'Blinding Lights', a: 'The Weeknd', y: 2019 },
  { t: 'Tusa', a: 'Karol G & Nicki Minaj', y: 2019 },
  { t: "Don't Start Now", a: 'Dua Lipa', y: 2019 },

  // ---------------------------------------------------------------- 2020s
  { t: 'Dynamite', a: 'BTS', y: 2020 },
  { t: 'Levitating', a: 'Dua Lipa', y: 2020 },
  { t: 'Mood', a: '24kGoldn feat. iann dior', y: 2020 },
  { t: 'Savage Love (Laxed – Siren Beat)', a: 'Jawsh 685 & Jason Derulo', y: 2020 },
  { t: 'Dákiti', a: 'Bad Bunny & Jhayco', y: 2020 },
  { t: 'drivers license', a: 'Olivia Rodrigo', y: 2021 },
  { t: 'Stay', a: 'The Kid LAROI & Justin Bieber', y: 2021 },
  { t: 'Bad Habits', a: 'Ed Sheeran', y: 2021 },
  { t: 'Montero (Call Me by Your Name)', a: 'Lil Nas X', y: 2021 },
  { t: 'Easy On Me', a: 'Adele', y: 2021 },
  { t: 'Zitti e buoni', a: 'Måneskin', y: 2021 },
  { t: 'As It Was', a: 'Harry Styles', y: 2022 },
  { t: 'About Damn Time', a: 'Lizzo', y: 2022 },
  { t: 'Anti-Hero', a: 'Taylor Swift', y: 2022 },
  { t: 'Unholy', a: 'Sam Smith & Kim Petras', y: 2022 },
  { t: 'Calm Down', a: 'Rema', y: 2022 },
  { t: 'Tití Me Preguntó', a: 'Bad Bunny', y: 2022 },
  { t: 'Flowers', a: 'Miley Cyrus', y: 2023 },
  { t: 'Unicorn', a: 'Noa Kirel', y: 2023 },
  { t: 'Tattoo', a: 'Loreen', y: 2023 },
  { t: 'vampire', a: 'Olivia Rodrigo', y: 2023 },
  { t: 'Paint the Town Red', a: 'Doja Cat', y: 2023 },
  { t: 'Espresso', a: 'Sabrina Carpenter', y: 2024 },
  { t: 'Hurricane', a: 'Eden Golan', y: 2024 },
  { t: 'Birds of a Feather', a: 'Billie Eilish', y: 2024 },
  { t: 'Beautiful Things', a: 'Benson Boone', y: 2024 },
  { t: 'APT.', a: 'ROSÉ & Bruno Mars', y: 2024 },
  { t: 'Die with a Smile', a: 'Lady Gaga & Bruno Mars', y: 2024 },
  { t: 'New Day Will Rise', a: 'Yuval Raphael', y: 2025 },
  { t: 'Abracadabra', a: 'Lady Gaga', y: 2025 },
  { t: 'Golden', a: 'HUNTR/X', y: 2025 },
];

/** The Demo service's fictional songs (js/providers/demo.js) — a small offline test deck. */
export const DEMO_SONGS = [
  { t: 'Neon Orbit', a: 'Luma Vale', y: 2021 },
  { t: 'Paper Lanterns', a: 'The Quiet Tides', y: 2019 },
  { t: 'Circuit Heart', a: 'KAIRO', y: 2023 },
  { t: 'Slow Motion Summer', a: 'Juniper & June', y: 2018 },
  { t: 'Northbound', a: 'Atlas Fields', y: 2020 },
  { t: 'Glass Garden', a: 'Mira Sol', y: 2022 },
  { t: 'אור על המים', a: 'נועה ים', y: 2024 },
];

/** The song-deck choices (the "Songs" option on the start card). */
export const ERAS = {
  all: { name: 'All', from: 0, to: 9999 },
  old: { name: '60s–80s', from: 1960, to: 1989 },
  new: { name: '90s–now', from: 1990, to: 9999 },
};
