// © 2026 Roy Borkin. All rights reserved. See LICENSE.
// Hitster — the song deck. Well-known songs with the year they were ORIGINALLY released
// (first single or album that carried this recording). { t: title, a: artist, y: year } plus, for songs
// whose title is in another script, ta / aa: the title and artist as Latin-script services may list them.
// Israeli songs carry il: 1 (SONGS) or sit in IL_SONGS; ah = the artist's name in Hebrew for a song whose title
// is in Latin letters (shown when Hitster is in Hebrew). In Hebrew the game shows the Hebrew forms; in English
// the Latin ones (ta / aa) when the original is in another script.
// Songs with a disputed year (a late-December single that charted the next year, a re-recording
// that became the famous version, a B-side that became a hit years later…) were left out on purpose,
// so a correct guess never depends on trivia about release dates.
// UNVERIFIED: the years were written from memory without access to an online database (MusicBrainz was
// unreachable) — IL_SONGS especially. Check them with  node bridge/tools/verify-hit-years.mjs > report.txt
// (it checks SONGS and IL_SONGS, in both the Hebrew and the Latin spelling).
// The Demo music service has no real songs, so it gets its own deck: its fictional tracks and their years.
// Every song also has  g: genre ids (GENRES in hits-text.js: pop rock hiphop rnb dance disco country metal latin reggae
// jazz mizrahi israeli eurovision soundtrack children),  l: the language it's sung in ('en', 'he', 'fr', 'es'… — the
// main one for a song in two languages) and, where it's clear,  b: 1 for a band / duo / group, b: 0 for a solo artist
// (Bingo's "Solo or band?" category; collaborations of solo artists have none). The tags were written by hand.
// "Update song lists" adds more songs from Wikidata (hits-update.js) — they're merged with these, never replace them.

export const SONGS = [
  // ---------------------------------------------------------------- before 1950
  { t: 'Over the Rainbow', a: 'Judy Garland', y: 1939, b: 0, g: ['pop', 'soundtrack'], l: 'en' },
  { t: 'In the Mood', a: 'Glenn Miller', y: 1939, b: 0, g: ['jazz'], l: 'en' },
  { t: 'Strange Fruit', a: 'Billie Holiday', y: 1939, b: 0, g: ['jazz'], l: 'en' },
  { t: 'White Christmas', a: 'Bing Crosby', y: 1942, b: 0, g: ['jazz', 'pop', 'soundtrack'], l: 'en' },
  { t: 'La vie en rose', a: 'Édith Piaf', y: 1947, b: 0, g: ['pop'], l: 'fr' },

  // ---------------------------------------------------------------- 1950s
  { t: 'Unforgettable', a: 'Nat King Cole', y: 1951, b: 0, g: ['jazz', 'pop'], l: 'en' },
  { t: "That's Amore", a: 'Dean Martin', y: 1953, b: 0, g: ['pop', 'jazz'], l: 'en' },
  { t: 'Rock Around the Clock', a: 'Bill Haley & His Comets', y: 1954, b: 1, g: ['rock'], l: 'en' },
  { t: 'Sh-Boom', a: 'The Chords', y: 1954, b: 1, g: ['rnb'], l: 'en' },
  { t: 'Tutti Frutti', a: 'Little Richard', y: 1955, b: 0, g: ['rock'], l: 'en' },
  { t: 'Maybellene', a: 'Chuck Berry', y: 1955, b: 0, g: ['rock'], l: 'en' },
  { t: "Ain't That a Shame", a: 'Fats Domino', y: 1955, b: 0, g: ['rock', 'rnb'], l: 'en' },
  { t: 'Only You (And You Alone)', a: 'The Platters', y: 1955, b: 1, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Heartbreak Hotel', a: 'Elvis Presley', y: 1956, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Hound Dog', a: 'Elvis Presley', y: 1956, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Blue Suede Shoes', a: 'Carl Perkins', y: 1956, b: 0, g: ['rock'], l: 'en' },
  { t: 'Be-Bop-A-Lula', a: 'Gene Vincent', y: 1956, b: 0, g: ['rock'], l: 'en' },
  { t: 'I Walk the Line', a: 'Johnny Cash', y: 1956, b: 0, g: ['country'], l: 'en' },
  { t: 'Que Sera, Sera', a: 'Doris Day', y: 1956, b: 0, g: ['pop', 'soundtrack'], l: 'en' },
  { t: 'Long Tall Sally', a: 'Little Richard', y: 1956, b: 0, g: ['rock'], l: 'en' },
  { t: 'Blueberry Hill', a: 'Fats Domino', y: 1956, b: 0, g: ['rock', 'rnb'], l: 'en' },
  { t: 'Jailhouse Rock', a: 'Elvis Presley', y: 1957, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: "That'll Be the Day", a: 'The Crickets', y: 1957, b: 1, g: ['rock'], l: 'en' },
  { t: 'Peggy Sue', a: 'Buddy Holly', y: 1957, b: 0, g: ['rock'], l: 'en' },
  { t: 'Great Balls of Fire', a: 'Jerry Lee Lewis', y: 1957, b: 0, g: ['rock'], l: 'en' },
  { t: 'Wake Up Little Susie', a: 'The Everly Brothers', y: 1957, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Diana', a: 'Paul Anka', y: 1957, b: 0, g: ['pop'], l: 'en' },
  { t: 'Johnny B. Goode', a: 'Chuck Berry', y: 1958, b: 0, g: ['rock'], l: 'en' },
  { t: 'La Bamba', a: 'Ritchie Valens', y: 1958, b: 0, g: ['rock', 'latin'], l: 'es' },
  { t: 'Summertime Blues', a: 'Eddie Cochran', y: 1958, b: 0, g: ['rock'], l: 'en' },
  { t: 'Yakety Yak', a: 'The Coasters', y: 1958, b: 1, g: ['rnb', 'rock'], l: 'en' },
  { t: 'Nel blu, dipinto di blu', a: 'Domenico Modugno', y: 1958, b: 0, g: ['pop', 'eurovision'], l: 'it' },
  { t: 'Fever', a: 'Peggy Lee', y: 1958, b: 0, g: ['jazz'], l: 'en' },
  { t: 'All I Have to Do Is Dream', a: 'The Everly Brothers', y: 1958, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Splish Splash', a: 'Bobby Darin', y: 1958, b: 0, g: ['pop', 'jazz'], l: 'en' },
  { t: 'Rockin\' Robin', a: 'Bobby Day', y: 1958, b: 0, g: ['rock', 'rnb'], l: 'en' },
  { t: 'Mack the Knife', a: 'Bobby Darin', y: 1959, b: 0, g: ['pop', 'jazz'], l: 'en' },
  { t: "What'd I Say", a: 'Ray Charles', y: 1959, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Put Your Head on My Shoulder', a: 'Paul Anka', y: 1959, b: 0, g: ['pop'], l: 'en' },
  { t: 'Shout', a: 'The Isley Brothers', y: 1959, b: 1, g: ['rnb'], l: 'en' },
  { t: 'Take Five', a: 'The Dave Brubeck Quartet', y: 1959, b: 1, g: ['jazz'], l: 'en' },

  // ---------------------------------------------------------------- 1960s
  { t: 'Non, je ne regrette rien', a: 'Édith Piaf', y: 1960, b: 0, g: ['pop'], l: 'fr' },
  { t: "It's Now or Never", a: 'Elvis Presley', y: 1960, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Georgia on My Mind', a: 'Ray Charles', y: 1960, b: 0, g: ['rnb'], l: 'en' },
  { t: 'The Twist', a: 'Chubby Checker', y: 1960, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Only the Lonely', a: 'Roy Orbison', y: 1960, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Stand by Me', a: 'Ben E. King', y: 1961, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Hit the Road Jack', a: 'Ray Charles', y: 1961, b: 0, g: ['rnb'], l: 'en' },
  { t: "Can't Help Falling in Love", a: 'Elvis Presley', y: 1961, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Crazy', a: 'Patsy Cline', y: 1961, b: 0, g: ['country'], l: 'en' },
  { t: 'Runaway', a: 'Del Shannon', y: 1961, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'The Lion Sleeps Tonight', a: 'The Tokens', y: 1961, b: 1, g: ['pop', 'children'], l: 'en' },
  { t: 'Sukiyaki', a: 'Kyu Sakamoto', y: 1961, ta: '上を向いて歩こう', aa: '坂本九', b: 0, g: ['pop'], l: 'ja' },
  { t: 'Twist and Shout', a: 'The Isley Brothers', y: 1962, b: 1, g: ['rnb'], l: 'en' },
  { t: 'Love Me Do', a: 'The Beatles', y: 1962, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Green Onions', a: "Booker T. & the M.G.'s", y: 1962, b: 1, g: ['rnb'], l: 'en' },
  { t: 'The Loco-Motion', a: 'Little Eva', y: 1962, b: 0, g: ['pop'], l: 'en' },
  { t: "Big Girls Don't Cry", a: 'The Four Seasons', y: 1962, b: 1, g: ['pop'], l: 'en' },
  { t: 'Surfin\' Safari', a: 'The Beach Boys', y: 1962, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'She Loves You', a: 'The Beatles', y: 1963, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Be My Baby', a: 'The Ronettes', y: 1963, b: 1, g: ['pop'], l: 'en' },
  { t: 'Ring of Fire', a: 'Johnny Cash', y: 1963, b: 0, g: ['country'], l: 'en' },
  { t: 'Louie Louie', a: 'The Kingsmen', y: 1963, b: 1, g: ['rock'], l: 'en' },
  { t: 'Blowin\' in the Wind', a: 'Bob Dylan', y: 1963, b: 0, g: ['country', 'rock'], l: 'en' },
  { t: 'Oh, Pretty Woman', a: 'Roy Orbison', y: 1964, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'The House of the Rising Sun', a: 'The Animals', y: 1964, b: 1, g: ['rock'], l: 'en' },
  { t: 'Baby Love', a: 'The Supremes', y: 1964, b: 1, g: ['rnb', 'pop'], l: 'en' },
  { t: 'You Really Got Me', a: 'The Kinks', y: 1964, b: 1, g: ['rock'], l: 'en' },
  { t: "A Hard Day's Night", a: 'The Beatles', y: 1964, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'My Guy', a: 'Mary Wells', y: 1964, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Dancing in the Street', a: 'Martha and the Vandellas', y: 1964, b: 1, g: ['rnb'], l: 'en' },
  { t: 'The Girl from Ipanema', a: 'Stan Getz & João Gilberto', y: 1964, g: ['jazz', 'latin'], l: 'en' },
  { t: 'Downtown', a: 'Petula Clark', y: 1964, b: 0, g: ['pop'], l: 'en' },
  { t: 'Fly Me to the Moon', a: 'Frank Sinatra', y: 1964, b: 0, g: ['jazz', 'pop'], l: 'en' },
  { t: "(I Can't Get No) Satisfaction", a: 'The Rolling Stones', y: 1965, b: 1, g: ['rock'], l: 'en' },
  { t: 'Yesterday', a: 'The Beatles', y: 1965, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Like a Rolling Stone', a: 'Bob Dylan', y: 1965, b: 0, g: ['country', 'rock'], l: 'en' },
  { t: 'I Got You (I Feel Good)', a: 'James Brown', y: 1965, b: 0, g: ['rnb', 'disco'], l: 'en' },
  { t: 'Mr. Tambourine Man', a: 'The Byrds', y: 1965, b: 1, g: ['rock', 'country'], l: 'en' },
  { t: 'Unchained Melody', a: 'The Righteous Brothers', y: 1965, b: 1, g: ['rnb', 'pop'], l: 'en' },
  { t: 'My Generation', a: 'The Who', y: 1965, b: 1, g: ['rock'], l: 'en' },
  { t: 'In the Midnight Hour', a: 'Wilson Pickett', y: 1965, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Good Vibrations', a: 'The Beach Boys', y: 1966, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Paint It Black', a: 'The Rolling Stones', y: 1966, b: 1, g: ['rock'], l: 'en' },
  { t: 'River Deep – Mountain High', a: 'Ike & Tina Turner', y: 1966, b: 1, g: ['rnb'], l: 'en' },
  { t: "Reach Out I'll Be There", a: 'Four Tops', y: 1966, b: 1, g: ['rnb'], l: 'en' },
  { t: 'Sunny', a: 'Bobby Hebb', y: 1966, b: 0, g: ['rnb'], l: 'en' },
  { t: "I'm a Believer", a: 'The Monkees', y: 1966, b: 1, g: ['pop', 'rock'], l: 'en' },
  { t: 'Strangers in the Night', a: 'Frank Sinatra', y: 1966, b: 0, g: ['jazz', 'pop'], l: 'en' },
  { t: 'Wild Thing', a: 'The Troggs', y: 1966, b: 1, g: ['rock'], l: 'en' },
  { t: 'Respect', a: 'Aretha Franklin', y: 1967, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Light My Fire', a: 'The Doors', y: 1967, b: 1, g: ['rock'], l: 'en' },
  { t: 'Somebody to Love', a: 'Jefferson Airplane', y: 1967, b: 1, g: ['rock'], l: 'en' },
  { t: 'Happy Together', a: 'The Turtles', y: 1967, b: 1, g: ['pop', 'rock'], l: 'en' },
  { t: "Ain't No Mountain High Enough", a: 'Marvin Gaye & Tammi Terrell', y: 1967, g: ['rnb'], l: 'en' },
  { t: 'What a Wonderful World', a: 'Louis Armstrong', y: 1967, b: 0, g: ['jazz'], l: 'en' },
  { t: 'Purple Haze', a: 'The Jimi Hendrix Experience', y: 1967, b: 1, g: ['rock'], l: 'en' },
  { t: 'A Whiter Shade of Pale', a: 'Procol Harum', y: 1967, b: 1, g: ['rock'], l: 'en' },
  { t: 'Brown Eyed Girl', a: 'Van Morrison', y: 1967, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'All You Need Is Love', a: 'The Beatles', y: 1967, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Pata Pata', a: 'Miriam Makeba', y: 1967, b: 0, g: ['pop'], l: 'xh' },
  { t: 'San Francisco (Be Sure to Wear Flowers in Your Hair)', a: 'Scott McKenzie', y: 1967, b: 0, g: ['pop', 'country'], l: 'en' },
  { t: 'ירושלים של זהב', a: 'שולי נתן', y: 1967, ta: 'Yerushalayim Shel Zahav', aa: 'Shuli Natan', il: 1, b: 0, g: ['israeli'], l: 'he' },
  { t: 'Hey Jude', a: 'The Beatles', y: 1968, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: "(Sittin' On) The Dock of the Bay", a: 'Otis Redding', y: 1968, b: 0, g: ['rnb'], l: 'en' },
  { t: 'I Heard It Through the Grapevine', a: 'Marvin Gaye', y: 1968, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Born to Be Wild', a: 'Steppenwolf', y: 1968, b: 1, g: ['rock'], l: 'en' },
  { t: 'Mrs. Robinson', a: 'Simon & Garfunkel', y: 1968, b: 1, g: ['country', 'pop', 'soundtrack'], l: 'en' },
  { t: 'Sympathy for the Devil', a: 'The Rolling Stones', y: 1968, b: 1, g: ['rock'], l: 'en' },
  { t: 'Son of a Preacher Man', a: 'Dusty Springfield', y: 1968, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Here Comes the Sun', a: 'The Beatles', y: 1969, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Space Oddity', a: 'David Bowie', y: 1969, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Sugar, Sugar', a: 'The Archies', y: 1969, b: 1, g: ['pop'], l: 'en' },
  { t: 'Bad Moon Rising', a: 'Creedence Clearwater Revival', y: 1969, b: 1, g: ['rock'], l: 'en' },
  { t: "Je t'aime… moi non plus", a: 'Jane Birkin & Serge Gainsbourg', y: 1969, g: ['pop'], l: 'fr' },
  { t: 'Whole Lotta Love', a: 'Led Zeppelin', y: 1969, b: 1, g: ['rock'], l: 'en' },
  { t: 'Aquarius / Let the Sunshine In', a: 'The 5th Dimension', y: 1969, b: 1, g: ['pop', 'soundtrack'], l: 'en' },
  { t: 'שיר לשלום', a: 'להקת הנח"ל', y: 1969, ta: 'Shir LaShalom', aa: 'Lehakat HaNahal', il: 1, b: 1, g: ['israeli'], l: 'he' },

  // ---------------------------------------------------------------- 1970s
  { t: 'Let It Be', a: 'The Beatles', y: 1970, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Bridge over Troubled Water', a: 'Simon & Garfunkel', y: 1970, b: 1, g: ['country', 'pop'], l: 'en' },
  { t: 'ABC', a: 'The Jackson 5', y: 1970, b: 1, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Lola', a: 'The Kinks', y: 1970, b: 1, g: ['rock'], l: 'en' },
  { t: 'Paranoid', a: 'Black Sabbath', y: 1970, b: 1, g: ['metal', 'rock'], l: 'en' },
  { t: 'Your Song', a: 'Elton John', y: 1970, b: 0, g: ['pop', 'rock'], l: 'en' },
  { t: 'War', a: 'Edwin Starr', y: 1970, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Layla', a: 'Derek and the Dominos', y: 1970, b: 1, g: ['rock'], l: 'en' },
  { t: 'Imagine', a: 'John Lennon', y: 1971, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Stairway to Heaven', a: 'Led Zeppelin', y: 1971, b: 1, g: ['rock'], l: 'en' },
  { t: "What's Going On", a: 'Marvin Gaye', y: 1971, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Take Me Home, Country Roads', a: 'John Denver', y: 1971, b: 0, g: ['country'], l: 'en' },
  { t: 'American Pie', a: 'Don McLean', y: 1971, b: 0, g: ['country', 'rock'], l: 'en' },
  { t: 'Riders on the Storm', a: 'The Doors', y: 1971, b: 1, g: ['rock'], l: 'en' },
  { t: 'Brown Sugar', a: 'The Rolling Stones', y: 1971, b: 1, g: ['rock'], l: 'en' },
  { t: "Let's Stay Together", a: 'Al Green', y: 1971, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Superstition', a: 'Stevie Wonder', y: 1972, b: 0, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Lean on Me', a: 'Bill Withers', y: 1972, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Rocket Man', a: 'Elton John', y: 1972, b: 0, g: ['pop', 'rock'], l: 'en' },
  { t: 'Heart of Gold', a: 'Neil Young', y: 1972, b: 0, g: ['country', 'rock'], l: 'en' },
  { t: 'Walk on the Wild Side', a: 'Lou Reed', y: 1972, b: 0, g: ['rock'], l: 'en' },
  { t: 'Smoke on the Water', a: 'Deep Purple', y: 1972, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: "School's Out", a: 'Alice Cooper', y: 1972, b: 0, g: ['rock'], l: 'en' },
  { t: 'Piano Man', a: 'Billy Joel', y: 1973, b: 0, g: ['pop', 'rock'], l: 'en' },
  { t: 'Money', a: 'Pink Floyd', y: 1973, b: 1, g: ['rock'], l: 'en' },
  { t: 'Killing Me Softly with His Song', a: 'Roberta Flack', y: 1973, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Live and Let Die', a: 'Wings', y: 1973, b: 1, g: ['rock', 'soundtrack'], l: 'en' },
  { t: 'Sweet Home Alabama', a: 'Lynyrd Skynyrd', y: 1974, b: 1, g: ['rock', 'country'], l: 'en' },
  { t: 'Waterloo', a: 'ABBA', y: 1974, b: 1, g: ['pop', 'disco', 'eurovision'], l: 'en' },
  { t: 'Kung Fu Fighting', a: 'Carl Douglas', y: 1974, b: 0, g: ['disco'], l: 'en' },
  { t: 'Rock Your Baby', a: 'George McCrae', y: 1974, b: 0, g: ['disco'], l: 'en' },
  { t: 'Lady Marmalade', a: 'Labelle', y: 1974, b: 1, g: ['disco', 'rnb'], l: 'en' },
  { t: 'Rebel Rebel', a: 'David Bowie', y: 1974, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: "You're the First, the Last, My Everything", a: 'Barry White', y: 1974, b: 0, g: ['rnb', 'disco'], l: 'en' },
  { t: 'נתתי לה חיי', a: 'כוורת', y: 1974, ta: 'Natati La Chayai', aa: 'Kaveret', il: 1, b: 1, g: ['israeli', 'rock'], l: 'he' },
  { t: 'Bohemian Rhapsody', a: 'Queen', y: 1975, b: 1, g: ['rock'], l: 'en' },
  { t: 'Born to Run', a: 'Bruce Springsteen', y: 1975, b: 0, g: ['rock'], l: 'en' },
  { t: 'Wish You Were Here', a: 'Pink Floyd', y: 1975, b: 1, g: ['rock'], l: 'en' },
  { t: 'The Hustle', a: 'Van McCoy', y: 1975, b: 0, g: ['disco'], l: 'en' },
  { t: 'Love Will Keep Us Together', a: 'Captain & Tennille', y: 1975, b: 1, g: ['pop'], l: 'en' },
  { t: 'Mamma Mia', a: 'ABBA', y: 1975, b: 1, g: ['pop', 'disco'], l: 'en' },
  { t: 'Rhinestone Cowboy', a: 'Glen Campbell', y: 1975, b: 0, g: ['country'], l: 'en' },
  { t: 'Fly, Robin, Fly', a: 'Silver Convention', y: 1975, b: 1, g: ['disco'], l: 'en' },
  { t: 'Dancing Queen', a: 'ABBA', y: 1976, b: 1, g: ['pop', 'disco'], l: 'en' },
  { t: 'Hotel California', a: 'Eagles', y: 1976, b: 1, g: ['rock', 'country'], l: 'en' },
  { t: "Don't Go Breaking My Heart", a: 'Elton John & Kiki Dee', y: 1976, g: ['pop'], l: 'en' },
  { t: 'Blitzkrieg Bop', a: 'Ramones', y: 1976, b: 1, g: ['rock'], l: 'en' },
  { t: 'More Than a Feeling', a: 'Boston', y: 1976, b: 1, g: ['rock'], l: 'en' },
  { t: 'Car Wash', a: 'Rose Royce', y: 1976, b: 1, g: ['disco', 'rnb', 'soundtrack'], l: 'en' },
  { t: 'Daddy Cool', a: 'Boney M.', y: 1976, b: 1, g: ['disco'], l: 'en' },
  { t: 'Play That Funky Music', a: 'Wild Cherry', y: 1976, b: 1, g: ['disco'], l: 'en' },
  { t: 'If You Leave Me Now', a: 'Chicago', y: 1976, b: 1, g: ['pop', 'rock'], l: 'en' },
  { t: "Stayin' Alive", a: 'Bee Gees', y: 1977, b: 1, g: ['disco', 'soundtrack'], l: 'en' },
  { t: 'We Will Rock You', a: 'Queen', y: 1977, b: 1, g: ['rock'], l: 'en' },
  { t: 'Dreams', a: 'Fleetwood Mac', y: 1977, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'I Feel Love', a: 'Donna Summer', y: 1977, b: 0, g: ['disco', 'dance'], l: 'en' },
  { t: '"Heroes"', a: 'David Bowie', y: 1977, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'God Save the Queen', a: 'Sex Pistols', y: 1977, b: 1, g: ['rock'], l: 'en' },
  { t: 'Barracuda', a: 'Heart', y: 1977, b: 1, g: ['rock'], l: 'en' },
  { t: 'Lovely Day', a: 'Bill Withers', y: 1977, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Le Freak', a: 'Chic', y: 1978, b: 1, g: ['disco'], l: 'en' },
  { t: 'Y.M.C.A.', a: 'Village People', y: 1978, b: 1, g: ['disco'], l: 'en' },
  { t: 'I Will Survive', a: 'Gloria Gaynor', y: 1978, b: 0, g: ['disco'], l: 'en' },
  { t: 'Wuthering Heights', a: 'Kate Bush', y: 1978, b: 0, g: ['pop'], l: 'en' },
  { t: 'אבניבי', a: 'יזהר כהן והאלפבתא', y: 1978, ta: 'A-Ba-Ni-Bi', aa: 'Izhar Cohen & Alphabeta', il: 1, b: 1, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'Sultans of Swing', a: 'Dire Straits', y: 1978, b: 1, g: ['rock'], l: 'en' },
  { t: 'September', a: 'Earth, Wind & Fire', y: 1978, b: 1, g: ['disco', 'rnb'], l: 'en' },
  { t: 'Hopelessly Devoted to You', a: 'Olivia Newton-John', y: 1978, b: 0, g: ['pop', 'soundtrack'], l: 'en' },
  { t: "You're the One That I Want", a: 'John Travolta & Olivia Newton-John', y: 1978, g: ['pop', 'soundtrack'], l: 'en' },
  { t: 'Roxanne', a: 'The Police', y: 1978, b: 1, g: ['rock', 'reggae'], l: 'en' },
  { t: 'Another Brick in the Wall, Part 2', a: 'Pink Floyd', y: 1979, b: 1, g: ['rock'], l: 'en' },
  { t: 'הללויה', a: 'גלי עטרי וחלב ודבש', y: 1979, ta: 'Hallelujah', aa: 'Gali Atari & Milk and Honey', il: 1, b: 1, g: ['israeli', 'eurovision'], l: 'he' },
  { t: "Don't Stop 'Til You Get Enough", a: 'Michael Jackson', y: 1979, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Video Killed the Radio Star', a: 'The Buggles', y: 1979, b: 1, g: ['pop'], l: 'en' },
  { t: 'Highway to Hell', a: 'AC/DC', y: 1979, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'London Calling', a: 'The Clash', y: 1979, b: 1, g: ['rock'], l: 'en' },
  { t: "Rapper's Delight", a: 'The Sugarhill Gang', y: 1979, b: 1, g: ['hiphop', 'disco'], l: 'en' },
  { t: 'Ring My Bell', a: 'Anita Ward', y: 1979, b: 0, g: ['disco'], l: 'en' },
  { t: 'My Sharona', a: 'The Knack', y: 1979, b: 1, g: ['rock'], l: 'en' },
  { t: 'Pop Muzik', a: 'M', y: 1979, g: ['pop', 'dance'], l: 'en' },

  // ---------------------------------------------------------------- 1980s
  { t: 'Another One Bites the Dust', a: 'Queen', y: 1980, b: 1, g: ['rock'], l: 'en' },
  { t: 'Back in Black', a: 'AC/DC', y: 1980, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'Call Me', a: 'Blondie', y: 1980, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Celebration', a: 'Kool & the Gang', y: 1980, b: 1, g: ['disco', 'rnb'], l: 'en' },
  { t: 'Upside Down', a: 'Diana Ross', y: 1980, b: 0, g: ['disco', 'rnb'], l: 'en' },
  { t: 'Super Trouper', a: 'ABBA', y: 1980, b: 1, g: ['pop', 'disco'], l: 'en' },
  { t: 'Love Will Tear Us Apart', a: 'Joy Division', y: 1980, b: 1, g: ['rock'], l: 'en' },
  { t: 'Tainted Love', a: 'Soft Cell', y: 1981, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: "Don't Stop Believin'", a: 'Journey', y: 1981, b: 1, g: ['rock'], l: 'en' },
  { t: 'Bette Davis Eyes', a: 'Kim Carnes', y: 1981, b: 0, g: ['pop'], l: 'en' },
  { t: 'Physical', a: 'Olivia Newton-John', y: 1981, b: 0, g: ['pop'], l: 'en' },
  { t: "Don't You Want Me", a: 'The Human League', y: 1981, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: "Jessie's Girl", a: 'Rick Springfield', y: 1981, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Under Pressure', a: 'Queen & David Bowie', y: 1981, g: ['rock'], l: 'en' },
  { t: 'Billie Jean', a: 'Michael Jackson', y: 1982, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Eye of the Tiger', a: 'Survivor', y: 1982, b: 1, g: ['rock', 'soundtrack'], l: 'en' },
  { t: 'Africa', a: 'Toto', y: 1982, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Come On Eileen', a: 'Dexys Midnight Runners', y: 1982, b: 1, g: ['pop'], l: 'en' },
  { t: 'Sexual Healing', a: 'Marvin Gaye', y: 1982, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Da Da Da', a: 'Trio', y: 1982, b: 1, g: ['pop'], l: 'de' },
  { t: 'Felicità', a: 'Al Bano & Romina Power', y: 1982, b: 1, g: ['pop'], l: 'it' },
  { t: 'Every Breath You Take', a: 'The Police', y: 1983, b: 1, g: ['rock', 'reggae'], l: 'en' },
  { t: 'Sweet Dreams (Are Made of This)', a: 'Eurythmics', y: 1983, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: '99 Luftballons', a: 'Nena', y: 1983, g: ['pop'], l: 'de' },
  { t: 'Girls Just Want to Have Fun', a: 'Cyndi Lauper', y: 1983, b: 0, g: ['pop'], l: 'en' },
  { t: 'Total Eclipse of the Heart', a: 'Bonnie Tyler', y: 1983, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Blue Monday', a: 'New Order', y: 1983, b: 1, g: ['dance'], l: 'en' },
  { t: 'Karma Chameleon', a: 'Culture Club', y: 1983, b: 1, g: ['pop'], l: 'en' },
  { t: "Let's Dance", a: 'David Bowie', y: 1983, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Relax', a: 'Frankie Goes to Hollywood', y: 1983, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: 'חי', a: 'עפרה חזה', y: 1983, ta: 'Chai', aa: 'Ofra Haza', il: 1, b: 0, g: ['israeli', 'mizrahi', 'eurovision'], l: 'he' },
  { t: 'When Doves Cry', a: 'Prince', y: 1984, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Like a Virgin', a: 'Madonna', y: 1984, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Wake Me Up Before You Go-Go', a: 'Wham!', y: 1984, b: 1, g: ['pop'], l: 'en' },
  { t: 'Footloose', a: 'Kenny Loggins', y: 1984, b: 0, g: ['rock', 'soundtrack'], l: 'en' },
  { t: 'Ghostbusters', a: 'Ray Parker Jr.', y: 1984, b: 0, g: ['rnb', 'soundtrack'], l: 'en' },
  { t: 'Born in the U.S.A.', a: 'Bruce Springsteen', y: 1984, b: 0, g: ['rock'], l: 'en' },
  { t: 'I Just Called to Say I Love You', a: 'Stevie Wonder', y: 1984, b: 0, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Self Control', a: 'Laura Branigan', y: 1984, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Smalltown Boy', a: 'Bronski Beat', y: 1984, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: 'Careless Whisper', a: 'George Michael', y: 1984, b: 0, g: ['pop'], l: 'en' },
  { t: 'You Spin Me Round (Like a Record)', a: 'Dead or Alive', y: 1984, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: 'Take On Me', a: 'a-ha', y: 1985, b: 1, g: ['pop'], l: 'en' },
  { t: "Don't You (Forget About Me)", a: 'Simple Minds', y: 1985, b: 1, g: ['rock', 'soundtrack'], l: 'en' },
  { t: 'Money for Nothing', a: 'Dire Straits', y: 1985, b: 1, g: ['rock'], l: 'en' },
  { t: 'Rock Me Amadeus', a: 'Falco', y: 1985, b: 0, g: ['pop'], l: 'de' },
  { t: 'We Are the World', a: 'USA for Africa', y: 1985, b: 1, g: ['pop'], l: 'en' },
  { t: 'Everybody Wants to Rule the World', a: 'Tears for Fears', y: 1985, b: 1, g: ['pop'], l: 'en' },
  { t: 'Running Up That Hill (A Deal with God)', a: 'Kate Bush', y: 1985, b: 0, g: ['pop'], l: 'en' },
  { t: 'The Power of Love', a: 'Huey Lewis and the News', y: 1985, b: 1, g: ['rock', 'soundtrack'], l: 'en' },
  { t: "Livin' on a Prayer", a: 'Bon Jovi', y: 1986, b: 1, g: ['rock'], l: 'en' },
  { t: 'The Final Countdown', a: 'Europe', y: 1986, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'Walk Like an Egyptian', a: 'The Bangles', y: 1986, b: 1, g: ['pop', 'rock'], l: 'en' },
  { t: 'Sledgehammer', a: 'Peter Gabriel', y: 1986, b: 0, g: ['rock', 'pop'], l: 'en' },
  { t: 'Take My Breath Away', a: 'Berlin', y: 1986, b: 1, g: ['pop', 'soundtrack'], l: 'en' },
  { t: 'Kiss', a: 'Prince', y: 1986, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Danger Zone', a: 'Kenny Loggins', y: 1986, b: 0, g: ['rock', 'soundtrack'], l: 'en' },
  { t: 'Venus', a: 'Bananarama', y: 1986, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: 'Higher Love', a: 'Steve Winwood', y: 1986, b: 0, g: ['pop'], l: 'en' },
  { t: 'Never Gonna Give You Up', a: 'Rick Astley', y: 1987, b: 0, g: ['pop'], l: 'en' },
  { t: 'With or Without You', a: 'U2', y: 1987, b: 1, g: ['rock'], l: 'en' },
  { t: "Sweet Child o' Mine", a: "Guns N' Roses", y: 1987, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'I Wanna Dance with Somebody (Who Loves Me)', a: 'Whitney Houston', y: 1987, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Bamboléo', a: 'Gipsy Kings', y: 1987, b: 1, g: ['latin'], l: 'es' },
  { t: "Ella, elle l'a", a: 'France Gall', y: 1987, b: 0, g: ['pop'], l: 'fr' },
  { t: 'Pump Up the Volume', a: 'MARRS', y: 1987, b: 1, g: ['dance'], l: 'en' },
  { t: 'Need You Tonight', a: 'INXS', y: 1987, b: 1, g: ['rock'], l: 'en' },
  { t: "It's a Sin", a: 'Pet Shop Boys', y: 1987, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: "Don't Worry, Be Happy", a: 'Bobby McFerrin', y: 1988, b: 0, g: ['pop', 'jazz'], l: 'en' },
  { t: 'Fast Car', a: 'Tracy Chapman', y: 1988, b: 0, g: ['country'], l: 'en' },
  { t: 'Orinoco Flow', a: 'Enya', y: 1988, b: 0, g: ['pop'], l: 'en' },
  { t: 'Buffalo Stance', a: 'Neneh Cherry', y: 1988, b: 0, g: ['hiphop', 'pop'], l: 'en' },
  { t: 'The Only Way Is Up', a: 'Yazz', y: 1988, b: 0, g: ['dance'], l: 'en' },
  { t: 'Kokomo', a: 'The Beach Boys', y: 1988, b: 1, g: ['rock', 'pop', 'soundtrack'], l: 'en' },
  { t: 'Like a Prayer', a: 'Madonna', y: 1989, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Lambada', a: 'Kaoma', y: 1989, b: 1, g: ['latin', 'dance'], l: 'pt' },
  { t: 'Pump Up the Jam', a: 'Technotronic', y: 1989, b: 1, g: ['dance'], l: 'en' },
  { t: 'Love Shack', a: "The B-52's", y: 1989, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Another Day in Paradise', a: 'Phil Collins', y: 1989, b: 0, g: ['pop'], l: 'en' },
  { t: "Free Fallin'", a: 'Tom Petty', y: 1989, b: 0, g: ['rock'], l: 'en' },
  { t: 'Bust a Move', a: 'Young MC', y: 1989, b: 0, g: ['hiphop'], l: 'en' },

  // ---------------------------------------------------------------- 1990s
  { t: 'Vogue', a: 'Madonna', y: 1990, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Nothing Compares 2 U', a: "Sinéad O'Connor", y: 1990, b: 0, g: ['pop'], l: 'en' },
  { t: "U Can't Touch This", a: 'MC Hammer', y: 1990, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Enjoy the Silence', a: 'Depeche Mode', y: 1990, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Thunderstruck', a: 'AC/DC', y: 1990, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'Unbelievable', a: 'EMF', y: 1990, b: 1, g: ['dance', 'rock'], l: 'en' },
  { t: 'Wind of Change', a: 'Scorpions', y: 1990, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'Poison', a: 'Bell Biv DeVoe', y: 1990, b: 1, g: ['rnb'], l: 'en' },
  { t: 'Smells Like Teen Spirit', a: 'Nirvana', y: 1991, b: 1, g: ['rock'], l: 'en' },
  { t: 'Losing My Religion', a: 'R.E.M.', y: 1991, b: 1, g: ['rock'], l: 'en' },
  { t: '(Everything I Do) I Do It for You', a: 'Bryan Adams', y: 1991, b: 0, g: ['rock', 'soundtrack'], l: 'en' },
  { t: 'Black or White', a: 'Michael Jackson', y: 1991, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Enter Sandman', a: 'Metallica', y: 1991, b: 1, g: ['metal'], l: 'en' },
  { t: 'Give It Away', a: 'Red Hot Chili Peppers', y: 1991, b: 1, g: ['rock'], l: 'en' },
  { t: "I'm Too Sexy", a: 'Right Said Fred', y: 1991, b: 1, g: ['pop', 'dance'], l: 'en' },
  { t: 'Summertime', a: 'DJ Jazzy Jeff & The Fresh Prince', y: 1991, b: 1, g: ['hiphop'], l: 'en' },
  { t: 'I Will Always Love You', a: 'Whitney Houston', y: 1992, b: 0, g: ['pop', 'rnb', 'soundtrack'], l: 'en' },
  { t: 'Jump', a: 'Kris Kross', y: 1992, b: 1, g: ['hiphop'], l: 'en' },
  { t: 'Rhythm Is a Dancer', a: 'Snap!', y: 1992, b: 1, g: ['dance'], l: 'en' },
  { t: 'Killing in the Name', a: 'Rage Against the Machine', y: 1992, b: 1, g: ['metal', 'rock'], l: 'en' },
  { t: 'Creep', a: 'Radiohead', y: 1992, b: 1, g: ['rock'], l: 'en' },
  { t: 'Achy Breaky Heart', a: 'Billy Ray Cyrus', y: 1992, b: 0, g: ['country'], l: 'en' },
  { t: 'Baby Got Back', a: 'Sir Mix-a-Lot', y: 1992, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'End of the Road', a: 'Boyz II Men', y: 1992, b: 1, g: ['rnb'], l: 'en' },
  { t: 'What Is Love', a: 'Haddaway', y: 1993, b: 0, g: ['dance'], l: 'en' },
  { t: 'The Sign', a: 'Ace of Base', y: 1993, b: 1, g: ['pop', 'reggae'], l: 'en' },
  { t: 'Mr. Vain', a: 'Culture Beat', y: 1993, b: 1, g: ['dance'], l: 'en' },
  { t: "I'd Do Anything for Love (But I Won't Do That)", a: 'Meat Loaf', y: 1993, b: 0, g: ['rock'], l: 'en' },
  { t: 'No Limit', a: '2 Unlimited', y: 1993, b: 1, g: ['dance'], l: 'en' },
  { t: 'Mr. Jones', a: 'Counting Crows', y: 1993, b: 1, g: ['rock'], l: 'en' },
  { t: 'Loser', a: 'Beck', y: 1993, b: 0, g: ['rock'], l: 'en' },
  { t: 'Zombie', a: 'The Cranberries', y: 1994, b: 1, g: ['rock'], l: 'en' },
  { t: 'Basket Case', a: 'Green Day', y: 1994, b: 1, g: ['rock'], l: 'en' },
  { t: 'Love Is All Around', a: 'Wet Wet Wet', y: 1994, b: 1, g: ['pop', 'soundtrack'], l: 'en' },
  { t: 'Cotton Eye Joe', a: 'Rednex', y: 1994, b: 1, g: ['dance', 'country'], l: 'en' },
  { t: 'Black Hole Sun', a: 'Soundgarden', y: 1994, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'Stay (I Missed You)', a: 'Lisa Loeb', y: 1994, b: 0, g: ['pop'], l: 'en' },
  { t: 'Sabotage', a: 'Beastie Boys', y: 1994, b: 1, g: ['hiphop', 'rock'], l: 'en' },
  { t: 'Waterfalls', a: 'TLC', y: 1995, b: 1, g: ['rnb'], l: 'en' },
  { t: "Gangsta's Paradise", a: 'Coolio', y: 1995, b: 0, g: ['hiphop', 'soundtrack'], l: 'en' },
  { t: 'Wonderwall', a: 'Oasis', y: 1995, b: 1, g: ['rock'], l: 'en' },
  { t: 'You Oughta Know', a: 'Alanis Morissette', y: 1995, b: 0, g: ['rock'], l: 'en' },
  { t: 'Boombastic', a: 'Shaggy', y: 1995, b: 0, g: ['reggae'], l: 'en' },
  { t: 'Fantasy', a: 'Mariah Carey', y: 1995, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Common People', a: 'Pulp', y: 1995, b: 1, g: ['rock'], l: 'en' },
  { t: 'Back for Good', a: 'Take That', y: 1995, b: 1, g: ['pop'], l: 'en' },
  { t: 'Wannabe', a: 'Spice Girls', y: 1996, b: 1, g: ['pop'], l: 'en' },
  { t: 'Killing Me Softly', a: 'Fugees', y: 1996, b: 1, g: ['hiphop', 'rnb'], l: 'en' },
  { t: 'Firestarter', a: 'The Prodigy', y: 1996, b: 1, g: ['dance'], l: 'en' },
  { t: 'No Diggity', a: 'Blackstreet', y: 1996, b: 1, g: ['rnb'], l: 'en' },
  { t: 'Virtual Insanity', a: 'Jamiroquai', y: 1996, b: 1, g: ['disco', 'pop'], l: 'en' },
  { t: 'Return of the Mack', a: 'Mark Morrison', y: 1996, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Barbie Girl', a: 'Aqua', y: 1997, b: 1, g: ['pop', 'dance', 'children'], l: 'en' },
  { t: 'My Heart Will Go On', a: 'Céline Dion', y: 1997, b: 0, g: ['pop', 'soundtrack'], l: 'en' },
  { t: 'Bitter Sweet Symphony', a: 'The Verve', y: 1997, b: 1, g: ['rock'], l: 'en' },
  { t: 'MMMBop', a: 'Hanson', y: 1997, b: 1, g: ['pop'], l: 'en' },
  { t: 'Tubthumping', a: 'Chumbawamba', y: 1997, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'Du hast', a: 'Rammstein', y: 1997, b: 1, g: ['metal'], l: 'de' },
  { t: 'Around the World', a: 'Daft Punk', y: 1997, b: 1, g: ['dance', 'disco'], l: 'en' },
  { t: 'Men in Black', a: 'Will Smith', y: 1997, b: 0, g: ['hiphop', 'soundtrack'], l: 'en' },
  { t: 'Torn', a: 'Natalie Imbruglia', y: 1997, b: 0, g: ['pop'], l: 'en' },
  { t: 'Song 2', a: 'Blur', y: 1997, b: 1, g: ['rock'], l: 'en' },
  { t: '...Baby One More Time', a: 'Britney Spears', y: 1998, b: 0, g: ['pop'], l: 'en' },
  { t: 'Believe', a: 'Cher', y: 1998, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'דיווה', a: 'דנה אינטרנשיונל', y: 1998, ta: 'Diva', aa: 'Dana International', il: 1, b: 0, g: ['israeli', 'dance', 'eurovision'], l: 'he' },
  { t: 'Iris', a: 'Goo Goo Dolls', y: 1998, b: 1, g: ['rock'], l: 'en' },
  { t: 'Blue (Da Ba Dee)', a: 'Eiffel 65', y: 1998, b: 1, g: ['dance'], l: 'en' },
  { t: 'The Boy Is Mine', a: 'Brandy & Monica', y: 1998, g: ['rnb'], l: 'en' },
  { t: 'Doo Wop (That Thing)', a: 'Lauryn Hill', y: 1998, b: 0, g: ['hiphop', 'rnb'], l: 'en' },
  { t: "Livin' la Vida Loca", a: 'Ricky Martin', y: 1999, b: 0, g: ['latin', 'pop'], l: 'en' },
  { t: 'Mambo No. 5 (A Little Bit of...)', a: 'Lou Bega', y: 1999, b: 0, g: ['latin', 'pop'], l: 'en' },
  { t: 'Smooth', a: 'Santana feat. Rob Thomas', y: 1999, g: ['rock', 'latin'], l: 'en' },
  { t: 'All Star', a: 'Smash Mouth', y: 1999, b: 1, g: ['rock'], l: 'en' },
  { t: 'Genie in a Bottle', a: 'Christina Aguilera', y: 1999, b: 0, g: ['pop'], l: 'en' },
  { t: 'I Want It That Way', a: 'Backstreet Boys', y: 1999, b: 1, g: ['pop'], l: 'en' },
  { t: 'My Name Is', a: 'Eminem', y: 1999, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Sandstorm', a: 'Darude', y: 1999, b: 0, g: ['dance'], l: 'en' },

  // ---------------------------------------------------------------- 2000s
  { t: 'Oops!... I Did It Again', a: 'Britney Spears', y: 2000, b: 0, g: ['pop'], l: 'en' },
  { t: 'Yellow', a: 'Coldplay', y: 2000, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'In the End', a: 'Linkin Park', y: 2000, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'Bye Bye Bye', a: '*NSYNC', y: 2000, b: 1, g: ['pop'], l: 'en' },
  { t: "It's My Life", a: 'Bon Jovi', y: 2000, b: 1, g: ['rock'], l: 'en' },
  { t: 'Beautiful Day', a: 'U2', y: 2000, b: 1, g: ['rock'], l: 'en' },
  { t: 'Ms. Jackson', a: 'OutKast', y: 2000, b: 1, g: ['hiphop'], l: 'en' },
  { t: 'Rock DJ', a: 'Robbie Williams', y: 2000, b: 0, g: ['pop'], l: 'en' },
  { t: 'Who Let the Dogs Out', a: 'Baha Men', y: 2000, b: 1, g: ['pop', 'dance', 'children'], l: 'en' },
  { t: "Can't Get You Out of My Head", a: 'Kylie Minogue', y: 2001, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Clint Eastwood', a: 'Gorillaz', y: 2001, b: 1, g: ['hiphop', 'rock'], l: 'en' },
  { t: "Fallin'", a: 'Alicia Keys', y: 2001, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Get Ur Freak On', a: 'Missy Elliott', y: 2001, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Chop Suey!', a: 'System of a Down', y: 2001, b: 1, g: ['metal'], l: 'en' },
  { t: 'Whenever, Wherever', a: 'Shakira', y: 2001, b: 0, g: ['latin', 'pop'], l: 'en' },
  { t: 'Family Affair', a: 'Mary J. Blige', y: 2001, b: 0, g: ['rnb'], l: 'en' },
  { t: 'How You Remind Me', a: 'Nickelback', y: 2001, b: 1, g: ['rock'], l: 'en' },
  { t: 'Lose Yourself', a: 'Eminem', y: 2002, b: 0, g: ['hiphop', 'soundtrack'], l: 'en' },
  { t: 'Complicated', a: 'Avril Lavigne', y: 2002, b: 0, g: ['pop', 'rock'], l: 'en' },
  { t: 'Hot in Herre', a: 'Nelly', y: 2002, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Aserejé', a: 'Las Ketchup', y: 2002, b: 1, g: ['latin', 'pop'], l: 'es' },
  { t: 'Cry Me a River', a: 'Justin Timberlake', y: 2002, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'A Thousand Miles', a: 'Vanessa Carlton', y: 2002, b: 0, g: ['pop'], l: 'en' },
  { t: 'Crazy in Love', a: 'Beyoncé', y: 2003, b: 0, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Hey Ya!', a: 'OutKast', y: 2003, b: 1, g: ['hiphop'], l: 'en' },
  { t: 'Seven Nation Army', a: 'The White Stripes', y: 2003, b: 1, g: ['rock'], l: 'en' },
  { t: 'In da Club', a: '50 Cent', y: 2003, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Dragostea din tei', a: 'O-Zone', y: 2003, b: 1, g: ['dance', 'pop'], l: 'ro' },
  { t: 'Toxic', a: 'Britney Spears', y: 2003, b: 0, g: ['pop'], l: 'en' },
  { t: 'Where Is the Love?', a: 'The Black Eyed Peas', y: 2003, b: 1, g: ['hiphop', 'pop'], l: 'en' },
  { t: 'Numb', a: 'Linkin Park', y: 2003, b: 1, g: ['rock', 'metal'], l: 'en' },
  { t: 'Mr. Brightside', a: 'The Killers', y: 2003, b: 1, g: ['rock'], l: 'en' },
  { t: 'Yeah!', a: 'Usher', y: 2004, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Gasolina', a: 'Daddy Yankee', y: 2004, b: 0, g: ['latin'], l: 'es' },
  { t: 'Take Me Out', a: 'Franz Ferdinand', y: 2004, b: 1, g: ['rock'], l: 'en' },
  { t: 'Boulevard of Broken Dreams', a: 'Green Day', y: 2004, b: 1, g: ['rock'], l: 'en' },
  { t: 'Since U Been Gone', a: 'Kelly Clarkson', y: 2004, b: 0, g: ['pop', 'rock'], l: 'en' },
  { t: 'Gold Digger', a: 'Kanye West', y: 2005, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Hung Up', a: 'Madonna', y: 2005, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Bad Day', a: 'Daniel Powter', y: 2005, b: 0, g: ['pop'], l: 'en' },
  { t: 'ממעמקים', a: 'הפרויקט של עידן רייכל', y: 2005, ta: "Mima'amakim", aa: 'The Idan Raichel Project', il: 1, b: 1, g: ['israeli'], l: 'he' },
  { t: "Hips Don't Lie", a: 'Shakira', y: 2006, b: 0, g: ['latin', 'pop'], l: 'en' },
  { t: 'Crazy', a: 'Gnarls Barkley', y: 2006, b: 1, g: ['rnb', 'pop'], l: 'en' },
  { t: 'SexyBack', a: 'Justin Timberlake', y: 2006, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Chasing Cars', a: 'Snow Patrol', y: 2006, b: 1, g: ['rock'], l: 'en' },
  { t: 'Rehab', a: 'Amy Winehouse', y: 2006, b: 0, g: ['rnb', 'jazz'], l: 'en' },
  { t: 'Maneater', a: 'Nelly Furtado', y: 2006, b: 0, g: ['pop'], l: 'en' },
  { t: 'Smile', a: 'Lily Allen', y: 2006, b: 0, g: ['pop'], l: 'en' },
  { t: 'Umbrella', a: 'Rihanna', y: 2007, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Becoming Insane', a: 'Infected Mushroom', y: 2007, ah: 'אינפקטד מאשרום', il: 1, b: 1, g: ['dance', 'israeli', 'metal'], l: 'en' },
  { t: 'Ruby', a: 'Kaiser Chiefs', y: 2007, b: 1, g: ['rock'], l: 'en' },
  { t: 'Bleeding Love', a: 'Leona Lewis', y: 2007, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Paper Planes', a: 'M.I.A.', y: 2007, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Viva la Vida', a: 'Coldplay', y: 2008, b: 1, g: ['rock', 'pop'], l: 'en' },
  { t: 'I Kissed a Girl', a: 'Katy Perry', y: 2008, b: 0, g: ['pop'], l: 'en' },
  { t: 'Just Dance', a: 'Lady Gaga', y: 2008, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Poker Face', a: 'Lady Gaga', y: 2008, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Single Ladies (Put a Ring on It)', a: 'Beyoncé', y: 2008, b: 0, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Sex on Fire', a: 'Kings of Leon', y: 2008, b: 1, g: ['rock'], l: 'en' },
  { t: 'Mercy', a: 'Duffy', y: 2008, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Love Story', a: 'Taylor Swift', y: 2008, b: 0, g: ['pop', 'country'], l: 'en' },
  { t: 'האש בעינייך', a: 'בועז מעודה', y: 2008, ta: 'The Fire in Your Eyes', aa: 'Boaz Mauda', il: 1, b: 0, g: ['israeli', 'mizrahi', 'eurovision'], l: 'he' },
  { t: 'I Gotta Feeling', a: 'The Black Eyed Peas', y: 2009, b: 1, g: ['hiphop', 'pop'], l: 'en' },
  { t: 'Empire State of Mind', a: 'Jay-Z & Alicia Keys', y: 2009, g: ['hiphop'], l: 'en' },
  { t: 'Party in the U.S.A.', a: 'Miley Cyrus', y: 2009, b: 0, g: ['pop'], l: 'en' },
  { t: 'Fireflies', a: 'Owl City', y: 2009, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'TiK ToK', a: 'Kesha', y: 2009, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Down', a: 'Jay Sean', y: 2009, b: 0, g: ['rnb'], l: 'en' },
  { t: 'Bad Romance', a: 'Lady Gaga', y: 2009, b: 0, g: ['pop', 'dance'], l: 'en' },

  // ---------------------------------------------------------------- 2010s
  { t: 'Rolling in the Deep', a: 'Adele', y: 2010, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Waka Waka (This Time for Africa)', a: 'Shakira', y: 2010, b: 0, g: ['latin', 'pop'], l: 'en' },
  { t: 'Danza Kuduro', a: 'Don Omar', y: 2010, b: 0, g: ['latin', 'dance'], l: 'es' },
  { t: 'Firework', a: 'Katy Perry', y: 2010, b: 0, g: ['pop'], l: 'en' },
  { t: 'Only Girl (In the World)', a: 'Rihanna', y: 2010, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Love the Way You Lie', a: 'Eminem feat. Rihanna', y: 2010, g: ['hiphop'], l: 'en' },
  { t: 'Dynamite', a: 'Taio Cruz', y: 2010, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Just the Way You Are', a: 'Bruno Mars', y: 2010, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Airplanes', a: 'B.o.B feat. Hayley Williams', y: 2010, g: ['hiphop', 'pop'], l: 'en' },
  { t: 'מילים', a: 'הראל סקעת', y: 2010, ta: 'Milim', aa: 'Harel Skaat', il: 1, b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'Someone Like You', a: 'Adele', y: 2011, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Party Rock Anthem', a: 'LMFAO', y: 2011, b: 1, g: ['dance', 'hiphop'], l: 'en' },
  { t: 'Moves Like Jagger', a: 'Maroon 5', y: 2011, b: 1, g: ['pop'], l: 'en' },
  { t: 'Ai Se Eu Te Pego', a: 'Michel Teló', y: 2011, b: 0, g: ['latin'], l: 'pt' },
  { t: 'Somebody That I Used to Know', a: 'Gotye', y: 2011, b: 0, g: ['pop'], l: 'en' },
  { t: 'Titanium', a: 'David Guetta feat. Sia', y: 2011, g: ['dance'], l: 'en' },
  { t: 'Call Me Maybe', a: 'Carly Rae Jepsen', y: 2011, b: 0, g: ['pop'], l: 'en' },
  { t: 'Gangnam Style', a: 'PSY', y: 2012, b: 0, g: ['pop', 'dance'], l: 'ko' },
  { t: 'Diamonds', a: 'Rihanna', y: 2012, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Thrift Shop', a: 'Macklemore & Ryan Lewis', y: 2012, b: 1, g: ['hiphop'], l: 'en' },
  { t: 'Locked Out of Heaven', a: 'Bruno Mars', y: 2012, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Euphoria', a: 'Loreen', y: 2012, b: 0, g: ['pop', 'dance', 'eurovision'], l: 'en' },
  { t: 'I Knew You Were Trouble', a: 'Taylor Swift', y: 2012, b: 0, g: ['pop', 'country'], l: 'en' },
  { t: 'Skyfall', a: 'Adele', y: 2012, b: 0, g: ['pop', 'rnb', 'soundtrack'], l: 'en' },
  { t: 'Get Lucky', a: 'Daft Punk', y: 2013, b: 1, g: ['dance', 'disco'], l: 'en' },
  { t: 'Wake Me Up', a: 'Avicii', y: 2013, b: 0, g: ['dance'], l: 'en' },
  { t: 'Royals', a: 'Lorde', y: 2013, b: 0, g: ['pop'], l: 'en' },
  { t: 'Happy', a: 'Pharrell Williams', y: 2013, b: 0, g: ['pop', 'soundtrack', 'children'], l: 'en' },
  { t: 'Blurred Lines', a: 'Robin Thicke', y: 2013, b: 0, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Counting Stars', a: 'OneRepublic', y: 2013, b: 1, g: ['pop'], l: 'en' },
  { t: 'Let It Go', a: 'Idina Menzel', y: 2013, b: 0, g: ['soundtrack', 'children'], l: 'en' },
  { t: 'Wrecking Ball', a: 'Miley Cyrus', y: 2013, b: 0, g: ['pop'], l: 'en' },
  { t: 'Stolen Dance', a: 'Milky Chance', y: 2013, b: 1, g: ['pop'], l: 'en' },
  { t: 'Uptown Funk', a: 'Mark Ronson feat. Bruno Mars', y: 2014, g: ['disco', 'pop'], l: 'en' },
  { t: 'Shake It Off', a: 'Taylor Swift', y: 2014, b: 0, g: ['pop', 'country'], l: 'en' },
  { t: 'All About That Bass', a: 'Meghan Trainor', y: 2014, b: 0, g: ['pop'], l: 'en' },
  { t: 'Bailando', a: 'Enrique Iglesias', y: 2014, b: 0, g: ['latin'], l: 'es' },
  { t: 'Rather Be', a: 'Clean Bandit', y: 2014, b: 1, g: ['dance', 'pop'], l: 'en' },
  { t: 'Stay with Me', a: 'Sam Smith', y: 2014, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Thinking Out Loud', a: 'Ed Sheeran', y: 2014, b: 0, g: ['pop'], l: 'en' },
  { t: 'Chandelier', a: 'Sia', y: 2014, b: 0, g: ['pop'], l: 'en' },
  { t: 'Hello', a: 'Adele', y: 2015, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'See You Again', a: 'Wiz Khalifa feat. Charlie Puth', y: 2015, g: ['hiphop', 'soundtrack'], l: 'en' },
  { t: 'Lean On', a: 'Major Lazer & DJ Snake', y: 2015, g: ['dance'], l: 'en' },
  { t: 'Golden Boy', a: 'Nadav Guedj', y: 2015, ah: 'נדב גדג\'', il: 1, b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },
  { t: 'Sorry', a: 'Justin Bieber', y: 2015, b: 0, g: ['pop'], l: 'en' },
  { t: 'Hotline Bling', a: 'Drake', y: 2015, b: 0, g: ['hiphop'], l: 'en' },
  { t: "Can't Feel My Face", a: 'The Weeknd', y: 2015, b: 0, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Love Me Like You Do', a: 'Ellie Goulding', y: 2015, b: 0, g: ['pop', 'soundtrack'], l: 'en' },
  { t: 'Faded', a: 'Alan Walker', y: 2015, b: 0, g: ['dance'], l: 'en' },
  { t: 'Cheap Thrills', a: 'Sia', y: 2016, b: 0, g: ['pop'], l: 'en' },
  { t: 'Closer', a: 'The Chainsmokers', y: 2016, b: 1, g: ['dance', 'pop'], l: 'en' },
  { t: "Can't Stop the Feeling!", a: 'Justin Timberlake', y: 2016, b: 0, g: ['pop', 'rnb', 'soundtrack', 'children'], l: 'en' },
  { t: 'This Is What You Came For', a: 'Calvin Harris', y: 2016, b: 0, g: ['dance'], l: 'en' },
  { t: 'Heathens', a: 'Twenty One Pilots', y: 2016, b: 1, g: ['rock', 'soundtrack'], l: 'en' },
  { t: 'Despacito', a: 'Luis Fonsi', y: 2017, b: 0, g: ['latin'], l: 'es' },
  { t: 'Shape of You', a: 'Ed Sheeran', y: 2017, b: 0, g: ['pop'], l: 'en' },
  { t: 'Mi Gente', a: 'J Balvin & Willy William', y: 2017, g: ['latin', 'dance'], l: 'es' },
  { t: 'Believer', a: 'Imagine Dragons', y: 2017, b: 1, g: ['rock'], l: 'en' },
  { t: 'Havana', a: 'Camila Cabello', y: 2017, b: 0, g: ['pop', 'latin'], l: 'en' },
  { t: 'HUMBLE.', a: 'Kendrick Lamar', y: 2017, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Something Just Like This', a: 'The Chainsmokers & Coldplay', y: 2017, b: 1, g: ['dance', 'pop'], l: 'en' },
  { t: 'New Rules', a: 'Dua Lipa', y: 2017, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Toy', a: 'Netta', y: 2018, ah: 'נטע', il: 1, b: 0, g: ['pop', 'israeli', 'eurovision'], l: 'en' },
  { t: "God's Plan", a: 'Drake', y: 2018, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'Shallow', a: 'Lady Gaga & Bradley Cooper', y: 2018, g: ['soundtrack', 'rock'], l: 'en' },
  { t: 'Sicko Mode', a: 'Travis Scott', y: 2018, b: 0, g: ['hiphop'], l: 'en' },
  { t: 'thank u, next', a: 'Ariana Grande', y: 2018, b: 0, g: ['pop'], l: 'en' },
  { t: 'Taki Taki', a: 'DJ Snake', y: 2018, b: 0, g: ['latin', 'dance'], l: 'es' },
  { t: 'One Kiss', a: 'Calvin Harris & Dua Lipa', y: 2018, g: ['dance'], l: 'en' },
  { t: 'Sweet but Psycho', a: 'Ava Max', y: 2018, b: 0, g: ['pop'], l: 'en' },
  { t: 'bad guy', a: 'Billie Eilish', y: 2019, b: 0, g: ['pop'], l: 'en' },
  { t: 'Señorita', a: 'Shawn Mendes & Camila Cabello', y: 2019, g: ['pop', 'latin'], l: 'en' },
  { t: 'Dance Monkey', a: 'Tones and I', y: 2019, g: ['pop'], l: 'en' },
  { t: 'Arcade', a: 'Duncan Laurence', y: 2019, b: 0, g: ['pop', 'eurovision'], l: 'en' },
  { t: 'Blinding Lights', a: 'The Weeknd', y: 2019, b: 0, g: ['rnb', 'pop'], l: 'en' },
  { t: 'Tusa', a: 'Karol G & Nicki Minaj', y: 2019, g: ['latin'], l: 'es' },
  { t: "Don't Start Now", a: 'Dua Lipa', y: 2019, b: 0, g: ['pop', 'dance'], l: 'en' },

  // ---------------------------------------------------------------- 2020s
  { t: 'Dynamite', a: 'BTS', y: 2020, b: 1, g: ['pop'], l: 'en' },
  { t: 'Levitating', a: 'Dua Lipa', y: 2020, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Mood', a: '24kGoldn feat. iann dior', y: 2020, g: ['hiphop', 'pop'], l: 'en' },
  { t: 'Savage Love (Laxed – Siren Beat)', a: 'Jawsh 685 & Jason Derulo', y: 2020, g: ['pop', 'reggae'], l: 'en' },
  { t: 'Dákiti', a: 'Bad Bunny & Jhayco', y: 2020, g: ['latin'], l: 'es' },
  { t: 'drivers license', a: 'Olivia Rodrigo', y: 2021, b: 0, g: ['pop'], l: 'en' },
  { t: 'Stay', a: 'The Kid LAROI & Justin Bieber', y: 2021, g: ['pop'], l: 'en' },
  { t: 'Bad Habits', a: 'Ed Sheeran', y: 2021, b: 0, g: ['pop'], l: 'en' },
  { t: 'Montero (Call Me by Your Name)', a: 'Lil Nas X', y: 2021, b: 0, g: ['hiphop', 'pop'], l: 'en' },
  { t: 'Easy On Me', a: 'Adele', y: 2021, b: 0, g: ['pop', 'rnb'], l: 'en' },
  { t: 'Zitti e buoni', a: 'Måneskin', y: 2021, b: 1, g: ['rock', 'eurovision'], l: 'it' },
  { t: 'As It Was', a: 'Harry Styles', y: 2022, b: 0, g: ['pop'], l: 'en' },
  { t: 'About Damn Time', a: 'Lizzo', y: 2022, b: 0, g: ['pop', 'disco'], l: 'en' },
  { t: 'Anti-Hero', a: 'Taylor Swift', y: 2022, b: 0, g: ['pop', 'country'], l: 'en' },
  { t: 'Unholy', a: 'Sam Smith & Kim Petras', y: 2022, g: ['pop'], l: 'en' },
  { t: 'Calm Down', a: 'Rema', y: 2022, b: 0, g: ['pop', 'hiphop'], l: 'en' },
  { t: 'Tití Me Preguntó', a: 'Bad Bunny', y: 2022, b: 0, g: ['latin'], l: 'es' },
  { t: 'Flowers', a: 'Miley Cyrus', y: 2023, b: 0, g: ['pop'], l: 'en' },
  { t: 'Unicorn', a: 'Noa Kirel', y: 2023, ah: 'נועה קירל', il: 1, b: 0, g: ['pop', 'israeli', 'eurovision'], l: 'en' },
  { t: 'Tattoo', a: 'Loreen', y: 2023, b: 0, g: ['pop', 'dance', 'eurovision'], l: 'en' },
  { t: 'vampire', a: 'Olivia Rodrigo', y: 2023, b: 0, g: ['pop'], l: 'en' },
  { t: 'Paint the Town Red', a: 'Doja Cat', y: 2023, b: 0, g: ['hiphop', 'pop'], l: 'en' },
  { t: 'Espresso', a: 'Sabrina Carpenter', y: 2024, b: 0, g: ['pop'], l: 'en' },
  { t: 'Hurricane', a: 'Eden Golan', y: 2024, ah: 'עדן גולן', il: 1, b: 0, g: ['pop', 'israeli', 'eurovision'], l: 'en' },
  { t: 'Birds of a Feather', a: 'Billie Eilish', y: 2024, b: 0, g: ['pop'], l: 'en' },
  { t: 'Beautiful Things', a: 'Benson Boone', y: 2024, b: 0, g: ['pop'], l: 'en' },
  { t: 'APT.', a: 'ROSÉ & Bruno Mars', y: 2024, g: ['pop'], l: 'en' },
  { t: 'Die with a Smile', a: 'Lady Gaga & Bruno Mars', y: 2024, g: ['pop'], l: 'en' },
  { t: 'New Day Will Rise', a: 'Yuval Raphael', y: 2025, ah: 'יובל רפאל', il: 1, b: 0, g: ['pop', 'israeli', 'eurovision'], l: 'en' },
  { t: 'Abracadabra', a: 'Lady Gaga', y: 2025, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Golden', a: 'HUNTR/X', y: 2025, b: 1, g: ['pop', 'soundtrack', 'children'], l: 'en' },
];

/**
 * Israeli hits (the main deck when Hitster is in Hebrew, and the "Israeli hits" choice). Title and artist in Hebrew
 * (t, a) with the Latin spelling services use (ta, aa); songs titled in Latin letters carry the artist in Hebrew (ah).
 * The Israeli songs already in SONGS (il: 1) are part of this deck too — see ISRAELI below; none are repeated here.
 * Years from memory, not yet checked against MusicBrainz (see the note at the top).
 */
export const IL_SONGS = [
  // ---------------------------------------------------------------- 1960s
  { t: 'גבעת התחמושת', a: 'להקת פיקוד מרכז', y: 1968, ta: 'Givat HaTahmoshet', aa: 'Lehakat Pikud Merkaz', b: 1, g: ['israeli'], l: 'he' },
  { t: "Laisse-moi t'aimer", a: 'Mike Brant', y: 1969, ah: 'מייק בראנט', b: 0, g: ['pop', 'israeli'], l: 'fr' },
  { t: 'עושה שלום', a: 'אילן ואילנית', y: 1969, ta: 'Oseh Shalom', aa: 'Ilan & Ilanit', b: 1, g: ['israeli'], l: 'he' },

  // ---------------------------------------------------------------- 1970s
  { t: 'אהבתיה', a: 'שלמה ארצי', y: 1970, ta: 'Ahavtiha', aa: 'Shlomo Artzi', b: 0, g: ['israeli', 'rock'], l: 'he' },
  { t: 'בשנה הבאה', a: 'אילן ואילנית', y: 1970, ta: "Bashana Haba'ah", aa: 'Ilan & Ilanit', b: 1, g: ['israeli'], l: 'he' },
  { t: 'אני ואתה', a: 'אריק איינשטיין', y: 1971, ta: "Ani Ve'Ata", aa: 'Arik Einstein', b: 0, g: ['israeli', 'rock'], l: 'he' },
  { t: 'אי שם', a: 'אילנית', y: 1973, ta: 'Ey Sham', aa: 'Ilanit', b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'לו יהי', a: 'נעמי שמר', y: 1973, ta: 'Lu Yehi', aa: 'Naomi Shemer', b: 0, g: ['israeli'], l: 'he' },
  { t: 'יו יה', a: 'כוורת', y: 1973, ta: 'Yo Ya', aa: 'Kaveret', b: 1, g: ['israeli', 'rock'], l: 'he' },
  { t: 'גוליית', a: 'כוורת', y: 1973, ta: 'Goliath', aa: 'Kaveret', b: 1, g: ['israeli', 'rock'], l: 'he' },
  { t: 'את ואני', a: 'שלמה ארצי', y: 1975, ta: "At Ve'Ani", aa: 'Shlomo Artzi', b: 0, g: ['israeli', 'rock'], l: 'he' },
  { t: 'אמור שלום', a: 'שוקולד מנטה מסטיק', y: 1976, ta: 'Emor Shalom', aa: 'Chocolat Menta Mastik', b: 1, g: ['israeli'], l: 'he' },
  { t: 'סוף עונת התפוזים', a: 'תמוז', y: 1976, ta: 'Sof Onat HaTapuzim', aa: 'Tamouz', b: 1, g: ['israeli', 'rock'], l: 'he' },
  { t: 'אהבה היא שיר לשניים', a: 'אילנית', y: 1977, ta: 'Ahava Hi Shir LiShnayim', aa: 'Ilanit', b: 0, g: ['israeli'], l: 'he' },
  { t: 'יהיה טוב', a: 'דוד ברוזה', y: 1977, ta: 'Yihye Tov', aa: 'David Broza', b: 0, g: ['israeli'], l: 'he' },
  { t: 'שיר הפרחה', a: 'עפרה חזה', y: 1979, ta: 'Shir HaFrecha', aa: 'Ofra Haza', b: 0, g: ['israeli', 'mizrahi'], l: 'he' },

  // ---------------------------------------------------------------- 1980s
  { t: 'אלינור', a: 'זוהר ארגוב', y: 1980, ta: 'Elinor', aa: 'Zohar Argov', b: 0, g: ['mizrahi', 'israeli'], l: 'he' },
  { t: 'על כל אלה', a: 'נעמי שמר', y: 1980, ta: 'Al Kol Ele', aa: 'Naomi Shemer', b: 0, g: ['israeli'], l: 'he' },
  { t: 'הלילה', a: 'הכל עובר חביבי', y: 1981, ta: 'Halayla', aa: 'Hakol Over Habibi', b: 1, g: ['israeli'], l: 'he' },
  { t: 'הפרח בגני', a: 'זוהר ארגוב', y: 1982, ta: 'HaPerach BeGani', aa: 'Zohar Argov', b: 0, g: ['mizrahi', 'israeli'], l: 'he' },
  { t: 'הורה', a: 'אבי טולדנו', y: 1982, ta: 'Hora', aa: 'Avi Toledano', b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'אולה אולה', a: 'יזהר כהן', y: 1985, ta: 'Olé, Olé', aa: 'Izhar Cohen', b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'מחכים למשיח', a: 'שלום חנוך', y: 1985, ta: 'Mehakim LaMashiach', aa: 'Shalom Hanoch', b: 0, g: ['israeli', 'rock'], l: 'he' },
  { t: 'רכבת לילה לקהיר', a: 'משינה', y: 1985, ta: 'Rakevet Layla LeKahir', aa: 'Mashina', b: 1, g: ['israeli', 'rock'], l: 'he' },
  { t: 'יבוא יום', a: 'מוטי גלעדי ושרי צוריאל', y: 1986, ta: 'Yavo Yom', aa: 'Moti Giladi & Sarai Tzuriel', g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'אין לי ארץ אחרת', a: 'גלי עטרי', y: 1986, ta: 'Ein Li Eretz Acheret', aa: 'Gali Atari', b: 0, g: ['israeli'], l: 'he' },
  { t: 'שביל הבריחה', a: 'ריטה', y: 1986, ta: 'Shvil HaBricha', aa: 'Rita', b: 0, g: ['israeli'], l: 'he' },
  { t: 'שיר הבטלנים', a: 'דתנר וקושניר', y: 1987, ta: 'Shir Habatlanim', aa: 'Datner & Kushnir', b: 1, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'עבודה עברית', a: 'אהוד בנאי והפליטים', y: 1987, ta: 'Avoda Ivrit', aa: 'Ehud Banai & HaPlitim', b: 1, g: ['israeli', 'rock'], l: 'he' },
  { t: 'בן אדם', a: 'ירדנה ארזי', y: 1988, ta: 'Ben Adam', aa: 'Yardena Arazi', b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'דרך המלך', a: 'גילי וגלית', y: 1989, ta: 'Derech Hamelech', aa: 'Gili & Galit', b: 1, g: ['israeli', 'eurovision'], l: 'he' },

  // ---------------------------------------------------------------- 1990s
  { t: 'שרה ברחובות', a: 'ריטה', y: 1990, ta: 'Shara Barchovot', aa: 'Rita', b: 0, g: ['israeli'], l: 'he' },
  { t: 'כאן', a: 'הדואו דאץ', y: 1991, ta: 'Kan', aa: 'Duo Datz', b: 1, g: ['israeli', 'eurovision', 'dance'], l: 'he' },
  { t: 'זה רק ספורט', a: 'דפנה דקל', y: 1992, ta: 'Ze Rak Sport', aa: 'Dafna Dekel', b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'עכשיו מעונן', a: 'אביב גפן', y: 1992, ta: 'Achshav Meunan', aa: 'Aviv Geffen', b: 0, g: ['israeli', 'rock'], l: 'he' },
  { t: 'Temple of Love (1992)', a: 'The Sisters of Mercy & Ofra Haza', y: 1992, ah: 'הסיסטרס אוף מרסי ועפרה חזה', g: ['rock', 'israeli', 'metal'], l: 'en' },
  { t: 'שירו', a: "שרהל'ה שרון ולהקת שירו", y: 1993, ta: 'Shiru', aa: "Sarah'le Sharon & The Shiru Group", b: 1, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'סעידה סולטנה', a: 'דנה אינטרנשיונל', y: 1993, ta: 'Saida Sultana', aa: 'Dana International', b: 0, g: ['israeli', 'dance', 'mizrahi'], l: 'he' },
  { t: 'אמן', a: 'ליאורה', y: 1995, ta: 'Amen', aa: 'Liora', b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'Alabina', a: 'Ishtar & Los Niños de Sara', y: 1996, ah: 'אישתר ולוס ניניוס דה סרה', g: ['latin', 'dance', 'israeli'], l: 'ar' },
  { t: 'יום הולדת', a: 'להקת עדן', y: 1999, ta: 'Yom Huledet', aa: 'Eden', b: 1, g: ['israeli', 'rnb', 'eurovision'], l: 'he' },

  // ---------------------------------------------------------------- 2000s
  { t: 'Bliss', a: 'Infected Mushroom', y: 2000, ah: 'אינפקטד מאשרום', b: 1, g: ['dance', 'israeli'], l: 'en' },
  { t: 'שמח', a: 'פינג פונג', y: 2000, ta: 'Sameach', aa: 'Ping Pong', b: 1, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'אין דבר', a: 'טל סונדק', y: 2001, ta: 'Ein Davar', aa: 'Tal Sondak', b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'Light a Candle', a: 'Sarit Hadad', y: 2002, ah: 'שרית חדד', b: 0, g: ['israeli', 'eurovision', 'pop'], l: 'en' },
  { t: 'בואי', a: 'הפרויקט של עידן רייכל', y: 2002, ta: "Bo'ee", aa: 'The Idan Raichel Project', b: 1, g: ['israeli'], l: 'he' },
  { t: 'תקווה', a: 'סאבלימינל והצל', y: 2002, ta: 'Tikva', aa: 'Subliminal & HaTzel', b: 1, g: ['hiphop', 'israeli'], l: 'he' },
  { t: 'מילים לאהבה', a: 'ליאור נרקיס', y: 2003, ta: 'Words for Love', aa: 'Lior Narkis', b: 0, g: ['mizrahi', 'israeli', 'eurovision'], l: 'he' },
  { t: 'Converting Vegetarians', a: 'Infected Mushroom', y: 2003, ah: 'אינפקטד מאשרום', b: 1, g: ['dance', 'israeli'], l: 'en' },
  { t: 'להאמין', a: "דוד ד'אור", y: 2004, ta: "Le'ha'amin", aa: "David D'Or", b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'שירת הסטיקר', a: 'הדג נחש', y: 2004, ta: 'Shirat HaSticker', aa: 'Hadag Nahash', b: 1, g: ['hiphop', 'israeli'], l: 'he' },
  { t: 'השקט שנשאר', a: 'שירי מימון', y: 2005, ta: "HaSheket SheNish'ar", aa: 'Shiri Maimon', b: 0, g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'Together We Are One', a: 'Eddie Butler', y: 2006, ah: 'אדי באטלר', b: 0, g: ['israeli', 'eurovision'], l: 'en' },
  { t: 'Push the Button', a: 'Teapacks', y: 2007, ah: 'טיפקס', b: 1, g: ['israeli', 'eurovision'], l: 'en' },
  { t: 'New Soul', a: 'Yael Naim', y: 2007, ah: 'יעל נעים', b: 0, g: ['pop', 'israeli'], l: 'en' },
  { t: 'Reckoning Song', a: 'Asaf Avidan & the Mojos', y: 2008, ah: 'אסף אבידן והמוג׳וס', b: 1, g: ['rock', 'israeli'], l: 'en' },
  { t: 'There Must Be Another Way', a: 'Noa & Mira Awad', y: 2009, ah: 'נועה ומירה עווד', g: ['israeli', 'eurovision'], l: 'he' },
  { t: 'Smashing the Opponent', a: 'Infected Mushroom feat. Jonathan Davis', y: 2009, ah: 'אינפקטד מאשרום', g: ['dance', 'metal', 'israeli'], l: 'en' },

  // ---------------------------------------------------------------- 2010s
  { t: 'Ding Dong', a: 'Dana International', y: 2011, ah: 'דנה אינטרנשיונל', b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },
  { t: 'Time', a: 'Izabo', y: 2012, ah: 'איזבו', b: 1, g: ['israeli', 'rock', 'eurovision'], l: 'en' },
  { t: 'One Day / Reckoning Song (Wankelmut Remix)', a: 'Asaf Avidan & the Mojos', y: 2012, ah: 'אסף אבידן והמוג׳וס', b: 1, g: ['rock', 'israeli'], l: 'en' },
  { t: 'Different Pulses', a: 'Asaf Avidan', y: 2012, ah: 'אסף אבידן', b: 0, g: ['rock', 'israeli'], l: 'en' },
  { t: 'רק בשבילו', a: 'מורן מזור', y: 2013, ta: 'Rak Bishvilo', aa: 'Moran Mazor', b: 0, g: ['israeli', 'mizrahi', 'eurovision'], l: 'he' },
  { t: 'Same Heart', a: 'Mei Finegold', y: 2014, ah: 'מאי פיינגולד', b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },
  { t: 'Made of Stars', a: 'Hovi Star', y: 2016, ah: 'חובי סטאר', b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },
  { t: 'I Feel Alive', a: 'Imri Ziv', y: 2017, ah: 'אימרי זיו', b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },
  { t: 'טודו בום', a: 'סטטיק ובן אל תבורי', y: 2017, ta: 'Tudo Bom', aa: 'Static & Ben El Tavori', b: 1, g: ['israeli', 'pop'], l: 'he' },
  { t: 'קילר', a: 'נועה קירל', y: 2017, ta: 'Killer', aa: 'Noa Kirel', b: 0, g: ['israeli', 'pop'], l: 'he' },
  { t: 'Further Up (Na, Na, Na, Na, Na)', a: 'Static & Ben El feat. Pitbull', y: 2019, ah: 'סטטיק ובן אל ופיטבול', g: ['israeli', 'pop', 'latin'], l: 'en' },
  { t: 'Bassa Sababa', a: 'Netta', y: 2019, ah: 'נטע', b: 0, g: ['pop', 'israeli'], l: 'en' },
  { t: 'Home', a: 'Kobi Marimi', y: 2019, ah: 'קובי מרימי', b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },

  // ---------------------------------------------------------------- 2020s
  { t: 'Feker Libi', a: 'Eden Alene', y: 2020, ah: 'עדן אלנה', b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },
  { t: "Please Don't Suck", a: 'Noa Kirel', y: 2020, ah: 'נועה קירל', b: 0, g: ['pop', 'israeli'], l: 'en' },
  { t: 'Set Me Free', a: 'Eden Alene', y: 2021, ah: 'עדן אלנה', b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },
  { t: 'I.M', a: 'Michael Ben David', y: 2022, ah: 'מיכאל בן דוד', b: 0, g: ['israeli', 'pop', 'eurovision'], l: 'en' },
];

/** Every Israeli song: the ones in SONGS (il: 1) and IL_SONGS. */
export const ISRAELI = [...SONGS.filter((s) => s.il), ...IL_SONGS];

/** The Demo service's fictional songs (js/providers/demo.js) — a small offline test deck. */
export const DEMO_SONGS = [
  { t: 'Neon Orbit', a: 'Luma Vale', y: 2021, b: 0, g: ['pop', 'dance'], l: 'en' },
  { t: 'Paper Lanterns', a: 'The Quiet Tides', y: 2019, b: 1, g: ['rock'], l: 'en' },
  { t: 'Circuit Heart', a: 'KAIRO', y: 2023, b: 0, g: ['dance'], l: 'en' },
  { t: 'Slow Motion Summer', a: 'Juniper & June', y: 2018, b: 1, g: ['country', 'pop'], l: 'en' },
  { t: 'Northbound', a: 'Atlas Fields', y: 2020, b: 1, g: ['rock'], l: 'en' },
  { t: 'Glass Garden', a: 'Mira Sol', y: 2022, b: 0, g: ['pop'], l: 'en' },
  { t: 'אור על המים', a: 'נועה ים', y: 2024, b: 0, g: ['israeli'], l: 'he' },
];

/** The song-deck choices (the "Songs" option on the start card). */
export const ERAS = {
  all: { name: 'All', from: 0, to: 9999 },
  il: { name: 'Israeli hits', from: 0, to: 9999 },
  old: { name: '60s–80s', from: 1960, to: 1989 },
  new: { name: '90s–now', from: 1990, to: 9999 },
};
