// Board Games → Rules: short summaries of 40 games, written in our own words (not rulebook text).
// Each: { id, name, he?, cat: board|classic|party|cards, players, time, goal, setup, turn, special, end, tips }
// A section is a string (paragraph) or an array (bullet list). Editions and house rules vary — the notes say so.

export const CATS = { board: 'Board', classic: 'Classic', party: 'Party', cards: 'Cards' };
export const SECTIONS = [['goal', 'Goal'], ['setup', 'Setup'], ['turn', 'On your turn'], ['special', 'Special rules'], ['end', 'End & scoring'], ['tips', 'Tips']];

export const RULES = [
  // ------------------------------------------------------------------ board games
  { id: 'ticket-to-ride', name: 'Ticket to Ride', cat: 'board', players: '2–5', time: '45–60 min',
    goal: 'Score the most points by claiming railway routes across the map and connecting the cities on your secret destination tickets.',
    setup: ['Each player takes 45 trains of one colour and 4 train cards.', 'Deal 3 destination tickets to everyone; keep at least 2.', 'Lay 5 train cards face up next to the deck.'],
    turn: ['Do exactly one of three things:', 'Draw 2 train cards — from the face-up row or the deck. A face-up locomotive counts as your whole draw.', 'Claim a route — pay cards of the route’s colour equal to its length (grey routes take any one colour; locomotives are wild), then place your trains and score it at once.', 'Draw 3 destination tickets and keep at least 1.'],
    special: ['Route points: 1→1, 2→2, 3→4, 4→7, 5→10, 6→15.', 'Double routes: with 2–3 players only one side can be used; nobody may take both sides.', 'If 3 locomotives are ever face up, replace all 5 cards.'],
    end: ['When someone ends a turn with 2 or fewer trains, everyone (including them) gets one last turn.', 'Add completed tickets, subtract failed ones, and give 10 points for the longest continuous path. Ties go to most completed tickets.'],
    tips: ['Grab the long routes your tickets need before rivals block them.', 'Late in the game, new tickets are a gamble — only draw if you can finish them.'] },

  { id: 'catan', name: 'Catan', he: 'קטאן', cat: 'board', players: '3–4 (5–6 with extension)', time: '60–120 min',
    goal: 'Be the first to reach 10 victory points by building settlements, cities and roads on the island.',
    setup: ['Build the hex island and place number tokens.', 'In a snake order (1-2-3-4-4-3-2-1) each player places 2 settlements, each with a road.', 'Your second settlement earns one resource from each hex it touches.'],
    turn: ['Roll two dice. Every settlement next to a hex with that number collects 1 of its resource (a city collects 2).', 'Trade with other players, or with the bank at 4:1 (harbours give 3:1 or 2:1).', 'Build: road = brick + lumber; settlement = brick + lumber + wool + grain; city = 3 ore + 2 grain; development card = ore + wool + grain.'],
    special: ['Rolling 7: anyone holding more than 7 cards discards half (round down). Move the robber to a new hex — it blocks production — and steal a card from a player there.', 'Distance rule: no settlement may be on a corner next to another settlement.', 'Development cards: knights (move the robber), progress cards and hidden victory points.', 'Longest Road (5+ connected segments) and Largest Army (3+ knights) are worth 2 points each, and can be taken away.'],
    end: 'The game ends the moment a player reaches 10 points on their own turn.',
    tips: ['Spread over different numbers and resources; 6 and 8 roll most often.', 'Ore and grain are the keys to cities and development cards.'] },

  { id: 'monopoly', name: 'Monopoly', he: 'מונופול', cat: 'board', players: '2–8', time: '1–3 hours',
    goal: 'Buy, rent and trade properties to bankrupt everyone else — be the last player with money.',
    setup: ['Everyone starts with $1,500 (in most editions).', 'Put all tokens on GO; one player is the banker.'],
    turn: ['Roll two dice and move. Rolling doubles lets you go again — three doubles in a row sends you to jail.', 'Unowned property: buy it at the printed price, or the bank auctions it to everyone.', 'Owned property: pay the owner rent.', 'Chance and Community Chest: follow the card.', 'Passing GO pays you $200.'],
    special: ['Own a whole colour group to double the base rent and to build houses — evenly across the group; after 4 houses comes a hotel.', 'Jail: get out by paying $50, using a “Get Out of Jail Free” card, or rolling doubles (pay after the third failed try).', 'You can trade properties, money and cards with other players at any time.', 'Free Parking money is a house rule, not the official one.'],
    end: 'If you owe more than you can raise (by selling buildings and mortgaging), you are bankrupt and out. The last player left wins — or agree on a time limit and the richest wins.',
    tips: ['Orange and red are landed on often (they sit after jail).', 'Three houses on a group is where rent jumps most.'] },

  { id: 'clue', name: 'Clue / Cluedo', he: 'קלואדו', cat: 'board', players: '3–6', time: '45 min',
    goal: 'Find out who did it, with which weapon and in which room.',
    setup: ['Secretly put one suspect, one weapon and one room card into the envelope.', 'Deal out the remaining cards; everybody marks their own cards on a detective sheet.'],
    turn: ['Roll and move through the corridors, or take a secret passage between corner rooms.', 'When you enter a room, make a suggestion: “I suggest it was this person, with this weapon, in this room.” The named suspect and weapon move into the room.', 'Going around the table, the first player who holds one of the three cards must secretly show you one.'],
    special: ['Accusation: once per game, on your turn, name the three cards and check the envelope.', 'A wrong accusation knocks you out of solving — but you keep showing cards to others.'],
    end: 'The first correct accusation wins.',
    tips: ['Suggest cards you already hold to steer the questioning.', 'Watch who shows cards to whom — that is information too.'] },

  { id: 'risk', name: 'Risk', he: 'ריסק', cat: 'board', players: '2–6', time: '2–4 hours',
    goal: 'Conquer the world — or complete your secret mission in the mission version.',
    setup: 'Share out the territories and place starting armies according to the number of players.',
    turn: ['Reinforce: get armies equal to your territories ÷ 3 (at least 3), plus continent bonuses and any card sets you trade in.', 'Attack as often as you like from a territory with 2+ armies to a neighbouring enemy territory.', 'Fortify: move armies once between two of your connected territories.'],
    special: ['Battle: the attacker rolls up to 3 dice (always leaving one army behind), the defender up to 2. Compare highest with highest, then second with second — the higher die wins, ties go to the defender.', 'Take a territory and you must move in at least as many armies as dice you rolled.', 'Conquering at least one territory in a turn earns a card; sets of three trade for growing numbers of armies.'],
    end: 'You win when every territory is yours (or your mission is done).',
    tips: ['Australia and South America are small and easy to hold early.', 'Don’t spread too thin — borders cost armies.'] },

  { id: 'carcassonne', name: 'Carcassonne', he: 'קרקסון', cat: 'board', players: '2–5', time: '35–45 min',
    goal: 'Build the medieval landscape tile by tile and score the most with your followers (meeples).',
    setup: 'Start with the river or start tile face up; each player takes 7 followers of one colour.',
    turn: ['Draw a tile and place it so every edge matches its neighbours.', 'You may put one follower on a feature of that tile — road, city, monastery or field — if no one already occupies the connected feature.', 'Score any feature the tile just completed and take those followers back.'],
    special: ['Completed: road 1 per tile, city 2 per tile and per pennant, monastery 9 once surrounded.', 'Shared features go to whoever has the most followers on them; ties all score in full.'],
    end: 'When the last tile is placed, unfinished features score less (road 1, city 1 + 1 per pennant, monastery 1 per tile), and farmers score 3 for each completed city their field touches.',
    tips: ['Don’t spend all your followers early.', 'Sneak into a big city from a separate tile, then join it up.'] },

  { id: 'pandemic', name: 'Pandemic', he: 'פנדמיק', cat: 'board', players: '2–4 (co-op)', time: '45 min',
    goal: 'Work together to discover cures for four diseases before the world is overrun.',
    setup: 'Infect 9 cities (3, 2 and 1 cubes), give everyone a role and a few city cards, and shuffle Epidemic cards evenly into the player deck.',
    turn: ['Take 4 actions: move, fly (by spending city cards), build a research station, treat a disease (remove a cube), share a city card, or discover a cure (5 cards of one colour at a research station).', 'Draw 2 player cards — an Epidemic raises the infection rate, hits a new city hard and puts the discarded infections back on top.', 'Infect as many cities as the infection rate shows.'],
    special: ['An outbreak happens when a city would get a 4th cube of one colour: every neighbour gets a cube instead, and outbreaks can chain.', 'Hand limit: 7 cards.'],
    end: 'You all win when the 4 cures are found. You all lose after 8 outbreaks, if any disease runs out of cubes, or if the player deck runs out.',
    tips: ['Use every role’s special power.', 'Plan together — talk out loud each turn.'] },

  { id: 'azul', name: 'Azul', he: 'אזול', cat: 'board', players: '2–4', time: '30–45 min',
    goal: 'Tile the palace wall in the patterns that score most.',
    setup: 'Put 4 random tiles on each factory display (5 displays for 2 players, 7 for 3, 9 for 4).',
    turn: ['Take every tile of one colour from one display (push the rest to the middle) — or every tile of one colour from the middle.', 'Put them on one pattern line of your board. A line holds a single colour; extra tiles fall to the floor line and cost points.', 'The first player to take from the middle also takes the first-player marker (it counts as a floor tile).'],
    special: ['After a round, each full line moves one tile to the wall. It scores 1, or the number of tiles it joins in a row plus in a column.', 'A colour can appear only once in each wall row and column.'],
    end: 'The game ends after the round in which someone completes a horizontal row. Bonuses: +2 per complete row, +7 per complete column, +10 per colour placed five times.',
    tips: ['Avoid the floor — it hurts more than you think.', 'Watch what your opponents need and leave them only bad choices.'] },

  { id: 'scrabble', name: 'Scrabble', he: 'שבץ נא (גרסה עברית)', cat: 'board', players: '2–4', time: '50–90 min',
    goal: 'Score the most by forming crossword-style words with letter tiles.',
    setup: 'Each player draws 7 tiles. The first word must cover the centre star.',
    turn: ['Place tiles in one line (across or down) to make words that connect to the board, then score every word you formed.', 'Or swap some tiles with the bag, or pass.', 'Refill to 7 tiles.'],
    special: ['Premium squares (double/triple letter or word) count only on the turn they are covered.', 'Using all 7 tiles in one turn earns a 50-point bonus.', 'A challenged word that turns out invalid comes off the board and the turn scores nothing.'],
    end: 'The game ends when the bag is empty and someone plays their last tile (or everyone passes). Unplayed tiles are subtracted; the player who went out adds them to their score.',
    tips: ['Learn the two-letter words.', 'Keep a balanced rack of vowels and consonants.'] },

  { id: 'rummikub', name: 'Rummikub', he: 'רמיקוב', cat: 'board', players: '2–4', time: '45–60 min',
    goal: 'Be the first to play every tile from your rack.',
    setup: 'Each player takes 14 tiles face down (106 tiles: numbers 1–13 in four colours, twice, plus 2 jokers).',
    turn: ['Play tiles onto the table as sets: a group (3–4 tiles of the same number in different colours) or a run (3+ consecutive numbers of one colour).', 'If you can’t or won’t play, draw one tile.'],
    special: ['Your first meld must add up to at least 30 points using only your own tiles.', 'After that you may rearrange anything on the table, as long as every set is valid when your turn ends.', 'A joker on the table can be swapped for the real tile — then the joker must be used in the same turn.', 'Many play with a one-minute turn timer.'],
    end: 'When someone empties their rack, everyone else loses the value of their tiles (joker = 30) and the winner gains the total.',
    tips: ['Hold back a few tiles to play onto other sets later.', 'Look for ways to split long runs to free tiles.'] },

  { id: 'yahtzee', name: 'Yahtzee', cat: 'board', players: '1+', time: '20–30 min',
    goal: 'Fill all 13 boxes on the score sheet with the best possible dice combinations.',
    setup: 'Five dice and a score sheet per player.',
    turn: ['Roll up to three times; between rolls keep any dice and re-roll the rest.', 'Then you must write a score in one empty box — a zero if your dice don’t fit.'],
    special: ['Upper section: count only the chosen number (three 4s in Fours = 12). Reaching 63 or more earns a 35-point bonus.', 'Lower section: three/four of a kind (sum of all dice), full house 25, small straight (4 in a row) 30, large straight (5 in a row) 40, Yahtzee (five alike) 50, chance (any total).', 'Each extra Yahtzee after a 50 is worth +100 and acts as a joker for another box.'],
    end: 'After 13 rounds, the highest total wins.',
    tips: ['Go for the upper bonus: aim for three of each number.', 'Use Chance as a safety net, not too early.'] },

  { id: 'snakes-ladders', name: 'Snakes & Ladders', he: 'סולמות וחבלים', cat: 'board', players: '2–6', time: '15–30 min',
    goal: 'Be the first to reach the last square.',
    setup: 'All counters start before square 1.',
    turn: ['Roll a die and move that many squares.', 'Land at the foot of a ladder: climb up. Land on a snake’s head: slide down to its tail.'],
    special: ['Common house rules: a 6 rolls again, and you need the exact number to land on the final square.'],
    end: 'The first to reach the top square wins.',
    tips: ['It’s pure luck — perfect for little ones learning to count.'] },

  // ------------------------------------------------------------------ classics
  { id: 'chess', name: 'Chess', he: 'שחמט', cat: 'classic', players: '2', time: '10–60+ min',
    goal: 'Checkmate the opponent’s king: attack it so it has no legal escape.',
    setup: 'Each player has a light square in the right-hand corner; each queen starts on her own colour. White moves first.',
    turn: ['Move one piece. King: one square any way. Queen: any distance straight or diagonal. Rook: straight. Bishop: diagonal. Knight: an L, jumping over pieces. Pawn: forward one (two from its start), captures diagonally.'],
    special: ['Castling: king moves two squares toward an unmoved rook, which hops over — not out of, through, or into check, with nothing in between.', 'En passant: a pawn that rushes two squares can be captured as if it moved one, but only right away.', 'Promotion: a pawn reaching the last rank becomes any piece (usually a queen).', 'You may never leave your own king in check.'],
    end: 'Checkmate wins. Draws: stalemate (no legal move, not in check), threefold repetition, the 50-move rule, too little material, or agreement.',
    tips: ['Control the centre, develop knights and bishops, castle early.', 'Before each move ask: what does my opponent threaten?'] },

  { id: 'checkers', name: 'Checkers / Draughts', he: 'דמקה', cat: 'classic', players: '2', time: '20–40 min',
    goal: 'Capture all the opponent’s pieces or leave them with no move.',
    setup: '8×8 board, 12 pieces each on the dark squares of the three rows nearest you.',
    turn: ['Move a piece diagonally forward to an empty square.', 'Capture by jumping over an adjacent enemy piece to the empty square behind it; keep jumping if you can.'],
    special: ['Capturing is compulsory in standard rules.', 'A piece reaching the far row is crowned a king and moves (and captures) backwards too.', 'Variants: in many home and international versions men may capture backwards and kings “fly” any distance — agree first.'],
    end: 'You win when your opponent has no pieces or cannot move.',
    tips: ['Keep your back row as long as possible to stop kings.', 'Trade pieces when you are ahead.'] },

  { id: 'backgammon', name: 'Backgammon', he: 'שש-בש', cat: 'classic', players: '2', time: '20–40 min',
    goal: 'Bring all 15 of your checkers home and bear them off first.',
    setup: 'Standard start: 2 on the opponent’s 1-point (your 24), 5 on 13, 3 on 8, 5 on 6. Each rolls one die; the higher roll moves first using both numbers.',
    turn: ['Roll two dice and move checkers by each number (one checker may use both). Doubles give four moves.', 'You may not land on a point held by 2+ opposing checkers.'],
    special: ['Landing on a single opposing checker (a blot) hits it to the bar; it must re-enter in your home board before its owner can move anything else.', 'If you can use both numbers you must; if only one, use the larger if possible.', 'Bearing off starts once all your checkers are in your home board.', 'Optional doubling cube raises the stakes.'],
    end: 'First to bear off all checkers wins. A gammon (opponent bore off none) counts double; a backgammon (they still have a checker on the bar or in your home) triple.',
    tips: ['Make points in a row to build a prime.', 'Don’t leave blots within easy reach early on.'] },

  { id: 'connect-four', name: 'Connect Four', he: 'ארבע בשורה', cat: 'classic', players: '2', time: '10 min',
    goal: 'Line up four of your discs in a row — across, down or diagonally.',
    setup: 'Empty 7-column, 6-row grid; each player has discs of one colour.',
    turn: 'Drop one disc into any column that still has room; it falls to the lowest free space.',
    special: ['Block the opponent’s three-in-a-row immediately.'],
    end: 'The first four in a row wins; a full grid is a draw.',
    tips: ['Take the centre column early — it is part of the most lines.', 'Build two threats at once so only one can be blocked.'] },

  { id: 'battleship', name: 'Battleship', he: 'צוללות', cat: 'classic', players: '2', time: '20–30 min',
    goal: 'Sink the opponent’s whole fleet first.',
    setup: 'Secretly place your ships on a 10×10 grid (usually 5, 4, 3, 3 and 2 squares long), straight and not overlapping.',
    turn: ['Call a square, like “B7”. Your opponent answers hit or miss, and announces when a ship is sunk.', 'Mark your shots on your tracking grid.'],
    special: ['Salvo variant: fire one shot per ship you still have afloat.'],
    end: 'The first to sink every enemy ship wins.',
    tips: ['Search in a checkerboard pattern — every ship covers at least two squares.', 'After a hit, probe the four neighbours.'] },

  // ------------------------------------------------------------------ party & dexterity
  { id: 'twister', name: 'Twister', he: 'טוויסטר', cat: 'party', players: '2–4 + a caller', time: '10 min',
    goal: 'Stay standing longest while the spinner ties you in knots.',
    setup: 'Lay the mat flat. Players start at opposite ends with feet on the circles nearest them; one person spins.',
    turn: ['The caller spins and calls a limb and a colour, e.g. “right hand, red”.', 'Every player moves that hand or foot to a free circle of that colour.'],
    special: ['Two players can’t share a circle — the first one there keeps it.', 'If a limb is already on that colour, move it to another circle of the same colour.'],
    end: 'You’re out if you fall, or an elbow or knee touches the mat. The last player in wins.',
    tips: ['Keep your weight low and centred.', 'Use the app’s spinner — it can call out loud and auto-spin.'] },

  { id: 'jenga', name: 'Jenga', he: "ג'נגה", cat: 'party', players: '2+', time: '10–20 min',
    goal: 'Don’t be the one who knocks the tower down.',
    setup: 'Build a tower of 18 levels, three blocks each, every level crosswise to the one below.',
    turn: ['Using one hand at a time, pull out a block from any level below the top one.', 'Place it on top to continue the crosswise pattern.'],
    special: ['You may tap and nudge blocks to find a loose one — put back any you move but don’t take.', 'Your turn ends a few seconds after your block is placed, or when the next player touches the tower.'],
    end: 'Whoever makes the tower fall loses.',
    tips: ['Centre blocks are often loosest.', 'Push gently from one end with a single finger.'] },

  { id: 'codenames', name: 'Codenames', he: 'שם קוד', cat: 'party', players: '4–8+', time: '15 min',
    goal: 'Your team finds all of its secret agents among 25 words before the other team does.',
    setup: ['Two teams, each with one spymaster. Lay 25 word cards in a 5×5 grid.', 'Only the spymasters see the key card: 9 agents for the starting team, 8 for the other, 7 innocent bystanders and 1 assassin.'],
    turn: ['Your spymaster says one word and one number, like “ocean, 2”.', 'Teammates touch words one at a time: your agent — keep going (up to the number + 1); a bystander or the other team’s agent — your turn ends.'],
    special: ['Touching the assassin loses the game immediately.', 'Clues may not be the visible words themselves or parts of them.'],
    end: 'The first team to reveal all its agents wins.',
    tips: ['Spymaster: keep a straight face.', 'Guessers: remember last turn’s clue — leftover words still count.'] },

  { id: 'dixit', name: 'Dixit', he: 'דיקסיט', cat: 'party', players: '3–6 (8 in later editions)', time: '30 min',
    goal: 'Give clues that some — but not all — players will understand.',
    setup: 'Each player gets 6 picture cards and a voting set.',
    turn: ['The storyteller picks a card and gives a clue: a word, sentence, song or sound.', 'Everyone else secretly gives the storyteller a card from their hand that fits the clue.', 'The cards are shuffled and revealed; each player (not the storyteller) votes for the one they think is the storyteller’s.'],
    special: ['If everyone or no one finds it: storyteller scores 0, everyone else 2.', 'Otherwise the storyteller and each player who found it score 3; others score 1 per vote their card attracted.'],
    end: 'When the deck runs out (or someone reaches 30 points), the highest score wins.',
    tips: ['Be poetic, not literal.', 'Choose a decoy card that matches the clue’s feeling.'] },

  { id: 'jungle-speed', name: 'Jungle Speed', he: "ג'ונגל ספיד", cat: 'party', players: '2–10', time: '15 min',
    goal: 'Get rid of all your cards first by winning grabs for the wooden totem.',
    setup: 'Deal all 80 cards face down as evenly as possible (leftovers go under the totem). Put the totem in the middle.',
    turn: ['In order, flip the top card of your pile onto your face-up pile — turn it away from you so everyone sees it at the same time.', 'Whenever two face-up cards show the same symbol (the colour doesn’t matter), those two players race to grab the totem.'],
    special: ['The winner of a duel gives their face-up pile to the loser, who also takes back their own face-up pile.', 'Grabbing by mistake (or knocking the totem over) means taking everyone’s face-up cards — and whatever is under the totem.', 'Inward arrows: everyone grabs; the winner puts their face-up pile under the totem.', 'Outward arrows: everyone flips at once.', 'Coloured arrows: until the next duel, matching goes by colour instead of symbol.'],
    end: 'A player with no cards left is out and wins; keep playing for places if you like.',
    tips: ['Watch shapes, not colours — the designs are made to fool you.', 'Keep your hand near the totem but not touching.'] },

  { id: 'exploding-kittens', name: 'Exploding Kittens', he: 'חתולים מתפוצצים', cat: 'party', players: '2–5', time: '15 min',
    goal: 'Avoid drawing an Exploding Kitten — the last player alive wins.',
    setup: 'Everyone gets a Defuse card and a hand of cards; shuffle Exploding Kittens into the deck — one fewer than the number of players.',
    turn: ['Play as many cards as you like (or none), then draw one card to end your turn.'],
    special: ['Drew an Exploding Kitten? Play a Defuse and secretly put the kitten back anywhere in the deck. No Defuse — you explode and are out.', 'Attack: end your turn without drawing; the next player takes two turns. Skip: end your turn without drawing.', 'See the Future: peek at the top 3 cards. Shuffle: shuffle the deck. Favor: someone gives you a card of their choice.', 'Nope stops any action (and can itself be Noped). Pairs of cat cards steal a random card.'],
    end: 'The last player who hasn’t exploded wins.',
    tips: ['Save your Defuse until you really need it.', 'Count the cards left — the odds get scary.'] },

  // ------------------------------------------------------------------ card games
  { id: 'taki', name: 'Taki', he: 'טאקי', cat: 'cards', players: '2–8', time: '15–30 min',
    goal: 'The Israeli shedding game: be the first to get rid of all your cards.',
    setup: 'Deal 8 cards each and turn one card up to start the discard pile.',
    turn: ['Play a card that matches the top card’s colour, number or symbol.', 'Can’t (or won’t) play? Draw one card and the turn passes.'],
    special: ['TAKI (טאקי): open a run — play every card of that colour in one go, then close it.', 'Super Taki (סופר טאקי): a wild TAKI in the current colour.', 'Stop (עצור): the next player is skipped. Change Direction (שנה כיוון): play reverses.', 'Plus (פלוס): you must put down another card right away (draw if you can’t).', '+2 (פלוס 2): the next player draws 2 — or adds their own +2, passing a bigger stack along.', 'Change Colour (שנה צבע): wild — choose the colour.', 'Newer editions add King (מלך — goes on anything, cancels penalties, play again), +3 (everyone else draws 3) and the +3 Breaker (שובר 3+ — bounces a +3 back).', 'Say “last card” (קלף אחרון) when you have one left; families differ on the penalty for forgetting.'],
    end: 'The first player with no cards wins the round; play several rounds and count wins.',
    tips: ['Keep a colour changer for the end.', 'Agree on house rules first — finishing on an action card is often not allowed.'] },

  { id: 'uno', name: 'Uno', he: 'אונו', cat: 'cards', players: '2–10', time: '20–40 min',
    goal: 'Empty your hand first; score points from what the others still hold.',
    setup: 'Deal 7 cards each; turn one up to start the discard pile.',
    turn: ['Match the top card by colour, number or symbol, or play a Wild.', 'Can’t play? Draw one — if it can be played, you may play it.'],
    special: ['Skip: next player loses a turn. Reverse: change direction (with 2 players it acts as Skip). Draw Two: next player draws 2 and misses the turn.', 'Wild: choose the colour. Wild Draw Four: next player draws 4 — officially only allowed when you have no card of the current colour, and it can be challenged.', 'Say “UNO!” with one card left; get caught not saying it and draw 2.', 'Stacking Draw Twos is a popular house rule, not the official one.'],
    end: 'The round winner scores all cards left in other hands: numbers at face value, Skip/Reverse/Draw Two 20, Wilds 50. First to 500 wins.',
    tips: ['Hold Wilds for when you’re stuck.', 'Change the colour to one you have many of.'] },

  { id: 'poker', name: 'Poker — Texas Hold’em', he: 'פוקר', cat: 'cards', players: '2–10', time: 'any',
    goal: 'Win chips by holding the best five-card hand — or by making everyone else fold.',
    setup: 'Two players post small and big blinds. Each player gets 2 private cards.',
    turn: ['Betting round before the flop: fold, call, or raise.', 'The flop: 3 shared cards — betting. The turn: a 4th — betting. The river: a 5th — final betting.', 'In each round you can check (if nobody bet), bet, call, raise or fold.'],
    special: ['Hands, best first: royal flush, straight flush, four of a kind, full house, flush, straight, three of a kind, two pair, one pair, high card.', 'Use any 5 of the 7 cards (your 2 + the 5 shared). Suits never rank; ties are broken by kickers.', 'An ace can be low only in A-2-3-4-5.'],
    end: 'At the showdown the best hand takes the pot (split if tied). Play until one player has all the chips or you call time.',
    tips: ['Play few hands, but play them firmly.', 'Position matters: acting last tells you the most.'] },

  { id: 'blackjack', name: 'Blackjack (21)', he: "בלאק ג'ק", cat: 'cards', players: '1–7 + dealer', time: 'any',
    goal: 'Beat the dealer by getting closer to 21 without going over.',
    setup: 'Place bets; everyone gets two cards; the dealer shows one card and hides the other.',
    turn: ['Hit to take a card, or stand to stop.', 'Double down: double your bet and take exactly one more card.', 'Split: two cards of the same rank become two hands with a second bet.'],
    special: ['Number cards count face value, J/Q/K are 10, an ace is 1 or 11.', 'An ace plus a 10-value card is a blackjack — usually paid 3 to 2.', 'Going over 21 is a bust — you lose even if the dealer busts later.', 'The dealer must draw to 17 (tables differ on a “soft” 17).'],
    end: 'Higher total than the dealer wins even money; a tie is a push (bet returned).',
    tips: ['Stand on 12–16 when the dealer shows 2–6; hit when they show 7 or more.', 'Always split aces and 8s.'] },

  { id: 'gin-rummy', name: 'Rummy / Gin Rummy', he: 'רמי', cat: 'cards', players: '2 (Gin) / 2–6 (Rummy)', time: '30 min',
    goal: 'Form your cards into melds and leave as little “deadwood” as possible.',
    setup: 'Gin: deal 10 cards each, turn one up to start the discard pile.',
    turn: ['Draw the top card of the deck or the discard pile.', 'Discard one card.'],
    special: ['Melds: sets (3–4 cards of one rank) or runs (3+ in sequence, same suit). Aces are low.', 'Knock when your unmatched cards total 10 or less; going gin means no deadwood at all (bonus, often 25).', 'After a knock the opponent may lay off cards on the knocker’s melds. If they end up with equal or less deadwood, it’s an undercut and they score the bonus.', 'Classic Rummy lays melds on the table during play and ends when someone goes out.'],
    end: 'The knocker scores the difference in deadwood. Play to 100.',
    tips: ['Watch the discards to guess what your opponent collects.', 'Ditch high cards early.'] },

  { id: 'hearts', name: 'Hearts', cat: 'cards', players: '4 (3–6 possible)', time: '30–45 min',
    goal: 'Avoid taking hearts and the queen of spades — lowest score wins.',
    setup: 'Deal all 13 cards each; pass 3 cards — left, right, across, then no pass, repeating.',
    turn: ['The 2 of clubs leads the first trick. Follow suit if you can; otherwise play anything.', 'The highest card of the led suit takes the trick and leads next.'],
    special: ['Each heart is 1 point; the queen of spades is 13.', 'Hearts can’t be led until one has been played (unless you only have hearts). Many play that no points may be dropped on the first trick.', 'Shooting the moon: take every heart and the queen and everyone else gets 26 instead.'],
    end: 'When someone reaches 100, the lowest score wins.',
    tips: ['Get rid of a whole suit early so you can dump bad cards.', 'Pass high spades if you can’t protect the queen.'] },

  { id: 'spades', name: 'Spades', cat: 'cards', players: '4 (two teams)', time: '45–60 min',
    goal: 'Your partnership scores by taking exactly the tricks you bid.',
    setup: 'Deal 13 cards each; partners sit opposite. Everyone bids how many tricks they will take.',
    turn: ['Follow the suit led if you can. Spades are always trumps.', 'Spades can’t be led until one has been played on another suit.'],
    special: ['Making your team’s bid scores 10 per trick bid, plus 1 per extra trick (“bags”). Ten bags cost 100.', 'Missing the bid loses 10 per trick bid.', 'Nil: bid zero — +100 if you take no tricks, −100 if you take any.'],
    end: 'The first team to 500 wins.',
    tips: ['Bid carefully — bags add up.', 'Help a nil-bidding partner by taking tricks for them.'] },

  { id: 'go-fish', name: 'Go Fish', cat: 'cards', players: '2–6', time: '15 min',
    goal: 'Collect the most “books” — all four cards of a rank.',
    setup: 'Deal 7 cards each (5 with four or more players); the rest is the pond.',
    turn: ['Ask one player for a rank you already hold: “Do you have any 7s?”', 'If they do, they hand over all of them and you ask again. If not — “Go fish!” — draw from the pond. Drawing the rank you asked for lets you go again.'],
    special: ['Lay down each completed book.'],
    end: 'When all books are made, the player with the most wins.',
    tips: ['Remember what others asked for — they hold that rank.'] },

  { id: 'crazy-eights', name: 'Crazy Eights', cat: 'cards', players: '2–7', time: '15 min',
    goal: 'Be first to play all your cards. (Taki and Uno grew from this family.)',
    setup: 'Deal 5 cards each (7 with two players); turn one up.',
    turn: ['Play a card matching the top card’s suit or rank.', 'Can’t play? Draw until you can (some play “draw one”).'],
    special: ['Eights are wild: play one any time and name the next suit.'],
    end: 'The winner scores the cards left in other hands: 8s 50, faces 10, aces 1, others face value.',
    tips: ['Save your eights for the end.'] },

  { id: 'war', name: 'War', he: 'מלחמה', cat: 'cards', players: '2', time: '10–30 min',
    goal: 'Win all the cards.',
    setup: 'Split the deck evenly face down.',
    turn: 'Both flip their top card; the higher card (aces high) takes both, which go under the winner’s pile.',
    special: ['A tie means war: each puts 3 cards face down and one face up — the higher face-up card takes everything.'],
    end: 'Whoever runs out of cards loses (or set a time limit and count).',
    tips: ['No strategy — great for teaching numbers.'] },

  { id: 'klondike', name: 'Solitaire (Klondike)', he: 'סוליטר', cat: 'cards', players: '1', time: '10 min',
    goal: 'Move every card onto four foundation piles, one per suit, from ace up to king.',
    setup: 'Deal 7 tableau columns of 1 to 7 cards, only the top card of each face up. The rest is the stock.',
    turn: ['Build tableau columns downward in alternating colours (red 6 on black 7). Move sequences together.', 'Turn up cards from the stock one or three at a time onto the waste and play them.'],
    special: ['Only a king (or a sequence starting with one) may fill an empty column.', 'Flip any face-down card that becomes uncovered.'],
    end: 'You win when all 52 cards are on the foundations.',
    tips: ['Free up the big face-down columns first.', 'Don’t rush cards to the foundations if you still need them to build.'] },

  { id: 'president', name: 'President (Президент)', cat: 'cards', players: '4–7', time: '20–30 min',
    goal: 'Get rid of your cards first to become President — and avoid ending as the lowest rank.',
    setup: 'Deal all the cards. Usually 3 is lowest and 2 highest.',
    turn: ['The leader plays a single, pair, triple or four of a kind.', 'Each next player plays the same number of cards of a higher rank, or passes.', 'When everyone passes, the last to play clears the pile and leads again.'],
    special: ['Finishing order gives titles: President, Vice-President, …, the last one is the “Scum” (names vary).', 'Next deal: the Scum gives their best 2 cards to the President, who returns any 2; the vices swap 1.', 'Many house rules: 2s clear the pile, jokers, skipping on equal cards, revolutions.'],
    end: 'Play rounds as long as you like; titles carry over.',
    tips: ['Use your high cards to win control, then lead what you have most of.'] },

  { id: 'speed', name: 'Speed', cat: 'cards', players: '2', time: '5 min',
    goal: 'Get rid of all your cards before your opponent — no turns, just speed.',
    setup: 'Each player has a hand of 5 and a draw pile. Two centre cards face down, with two side piles of spares.',
    turn: ['Both flip a centre card at once. Play cards that are one higher or one lower than either centre card (suits don’t matter; king and ace connect).', 'Refill your hand to 5 from your own pile as you play.'],
    special: ['When neither player can move, both flip a new centre card from the side piles at the same time.'],
    end: 'The first to empty their hand and draw pile wins (often by slapping the smaller centre pile).',
    tips: ['Look at both centre piles all the time.'] },

  { id: 'spit', name: 'Spit', cat: 'cards', players: '2', time: '10 min',
    goal: 'Be the first to get rid of all your cards over several rounds.',
    setup: 'Each player lays out 5 stockpiles of 1 to 5 cards (top card face up); the rest is their spit pile.',
    turn: ['Both shout “Spit!” and flip a card into the centre to start two piles.', 'Play as fast as you can onto either centre pile, one rank up or down. Move cards between your own stockpiles too.'],
    special: ['When nobody can move, spit again.', 'When one player clears their stockpiles, both slap a centre pile — the faster player takes the smaller one; those cards form the next round’s deck.'],
    end: 'A player with no cards left at all wins.',
    tips: ['Free up face-down cards in your stockpiles quickly.'] },

  { id: 'old-maid', name: 'Old Maid', cat: 'cards', players: '2–8', time: '10 min',
    goal: 'Don’t be left holding the odd card.',
    setup: 'Remove one queen (or add a joker as the “maid”) and deal all the cards. Everyone discards their pairs.',
    turn: 'Draw a card, unseen, from your neighbour’s hand. If it makes a pair, discard the pair. Then they draw from their neighbour.',
    special: ['Shuffle your hand often so the maid can’t be tracked.'],
    end: 'Whoever ends with the unmatched queen (or joker) loses.',
    tips: ['Keep a straight face when someone reaches for the maid!'] },

  { id: 'yaniv', name: 'Yaniv', he: 'יניב', cat: 'cards', players: '2–5', time: '20–40 min',
    goal: 'The Israeli favourite: keep your hand total low and call “Yaniv” at the right moment. Lowest score wins.',
    setup: 'Deal 5 cards each (some play 7). Values: ace 1, 2–10 face value, J/Q/K 10, jokers 0.',
    turn: ['Discard one card, a set of the same rank, or a run of 3+ in one suit.', 'Then take one card: from the deck, or one of the cards the previous player just discarded (the end cards of a run).'],
    special: ['At the start of your turn, if your hand totals 7 or less (some play 5), you may call “Yaniv!” and everyone shows their hand.', 'Assaf: if anyone has the same or lower total, they call “Assaf!” — the caller takes a penalty (often 30) and the Assaf player scores 0.', 'Otherwise the caller scores 0 and everyone else adds their hand total.', 'Common rule: landing exactly on 50 or 100 halves your score (or takes 50 off).'],
    end: 'Players who pass the limit (100 or 200 — agree first) are out; the last player in, or the lowest score, wins.',
    tips: ['Dump high cards early; jokers are gold.', 'Count what others pick up from the discards.'] },

  { id: 'shithead', name: 'Shithead / Palace', cat: 'cards', players: '2–5', time: '15–30 min',
    goal: 'Get rid of all your cards — the last player holding cards is the “Shithead”.',
    setup: 'Each player gets 3 face-down cards, 3 face-up cards on top of them, and 3 in hand. Before starting you may swap hand cards with your face-up cards.',
    turn: ['Play one or more cards of the same rank, equal to or higher than the top of the pile.', 'Can’t play? Pick up the whole pile.', 'Draw back up to 3 cards while the deck lasts.'],
    special: ['2 resets the pile (anything may follow). 10 burns the pile — it’s removed and you play again. Four of a kind in a row also burns.', 'Popular extras: 7 means the next card must be 7 or lower; 8 or 3 is “invisible”.', 'When your hand and the deck are empty, play from your face-up cards, then the face-down ones blindly — if a blind card can’t be played, pick up the pile.'],
    end: 'Players drop out as they finish; the last one left is the Shithead (and deals next).',
    tips: ['Put 2s, 10s and aces face up — they rescue you late in the game.'] },
];
